"""STARTING POINT — copy into your app and rewrite the keys listed below.

Terms of use for an app sold through Apple with one-time purchases and no
subscription, in eleven languages.

REWRITE FOR YOUR APP, in every language:

    p_purchases      what you sell, and that none of it renews
    p_pro            your bundle product, or drop the paragraph
    p_content        only if users can bring content in
    h_music/p_music  third-party licences you actually ship — fonts, samples,
                     sound banks, art. Wrong attribution is the one mistake
                     here that can cost money.

CHECK, do not assume:

    p_refunds        the free-preview sentence describes a preview you have
    p_warranty       standard, and still worth reading once

The English entry governs; the renderer says so on every translation.
"""

TERMS = {
"en": {
 "title": "Terms of Use", "meta": "Terms of use for the TappyMusic iOS app.",
 "h": "Terms of Use",
 "updated": "Last updated 2&nbsp;August&nbsp;2026.",
 "p_eula": "TappyMusic is licensed, not sold, under Apple's {eula}, which applies in full. The terms below add to it and describe how this particular app behaves.",
 "eula": "Standard End User License Agreement",
 "h_purchases": "Purchases",
 "p_purchases": "Melody packs, importing your own songs, making your own cliparts and TappyMusic&nbsp;Pro are <strong>one-time purchases</strong>. There is no subscription and nothing renews. Every purchase is Family Shareable, so it is available to your Apple Family Sharing group.",
 "p_refunds": "Purchases are processed by Apple. Refunds are Apple's to grant, through {refund}. If a purchase is refunded or a family member stops sharing one, the app returns to the unpurchased state for that item — the free pack and each paid pack's free preview melody keep working.",
 "p_pro": "TappyMusic&nbsp;Pro includes everything the app sells: every melody pack, importing your own songs, and making your own cliparts. Those three are also sold separately; buying Pro after one of them does not refund the earlier purchase, so the shop shows what you already own.",
 "h_content": "Content you bring in",
 "p_content": "You can import MIDI files. Those files, and the songs made from them, stay on your device and are not uploaded anywhere. You are responsible for having the right to use any file you import. TappyMusic makes no claim of ownership over your imported songs and grants you no rights in anyone else's music.",
 "h_music": "The music that ships with the app",
 "p_music": "Every melody included in TappyMusic is a public-domain composition. The arrangements and the recordings-by-synthesis are ours. Instrument sounds come from {sf}, © 2000–2019 Frank&nbsp;Wen, Michael&nbsp;Cowgill and S.&nbsp;Christian&nbsp;Collins, used under the MIT licence.",
 "h_notdo": "What the app does not do",
 "p_notdo": "It collects no data, shows no advertising, contains no chat or social feature, and makes no network request of its own. See the {privacy} for the detail.",
 "privacy": "privacy policy",
 "h_warranty": "No warranty",
 "p_warranty": "The app is provided as is. To the extent permitted by law, and without limiting any rights you have under Apple's Standard EULA or under mandatory consumer law in your country, no warranty is given that it will be uninterrupted or error-free.",
 "h_changes": "Changes",
 "p_changes": "These terms may change with a new version of the app. The date above changes with them, and a material change will be described in that version's release notes.",
 "h_contact": "Contact",
 "governing": "",
},
"de": {
 "title": "Nutzungsbedingungen", "meta": "Nutzungsbedingungen für die iOS-App TappyMusic.",
 "h": "Nutzungsbedingungen",
 "updated": "Zuletzt aktualisiert am 2.&nbsp;August&nbsp;2026.",
 "p_eula": "TappyMusic wird lizenziert, nicht verkauft, und zwar unter Apples {eula}, die vollumfänglich gilt. Die folgenden Bedingungen ergänzen sie und beschreiben, wie sich diese App verhält.",
 "eula": "Standard-Endbenutzer-Lizenzvertrag",
 "h_purchases": "Käufe",
 "p_purchases": "Melodiepakete, der Import eigener Lieder, das Erstellen eigener Cliparts und TappyMusic&nbsp;Pro sind <strong>einmalige Käufe</strong>. Es gibt kein Abonnement, und nichts verlängert sich. Jeder Kauf ist über die Familienfreigabe teilbar und steht damit Ihrer Apple-Familiengruppe zur Verfügung.",
 "p_refunds": "Käufe werden von Apple abgewickelt. Über Rückerstattungen entscheidet Apple, über {refund}. Wird ein Kauf erstattet oder hört ein Familienmitglied auf, ihn zu teilen, kehrt die App für diesen Artikel in den ungekauften Zustand zurück — das kostenlose Paket und die kostenlose Vorschaumelodie jedes Kaufpakets funktionieren weiter.",
 "p_pro": "TappyMusic&nbsp;Pro enthält alles, was die App verkauft: jedes Melodiepaket, den Import eigener Lieder und das Erstellen eigener Cliparts. Diese drei sind auch einzeln erhältlich; wer Pro nach einem davon kauft, erhält den früheren Kauf nicht erstattet — deshalb zeigt der Shop, was Ihnen bereits gehört.",
 "h_content": "Inhalte, die Sie mitbringen",
 "p_content": "Sie können MIDI-Dateien importieren. Diese Dateien und die daraus entstehenden Lieder bleiben auf Ihrem Gerät und werden nirgendwohin hochgeladen. Sie sind dafür verantwortlich, das Recht zur Nutzung jeder importierten Datei zu haben. TappyMusic erhebt keinen Eigentumsanspruch an Ihren importierten Liedern und räumt Ihnen keine Rechte an fremder Musik ein.",
 "h_music": "Die Musik, die mit der App kommt",
 "p_music": "Jede in TappyMusic enthaltene Melodie ist eine gemeinfreie Komposition. Die Arrangements und die synthetisierten Aufnahmen stammen von uns. Die Instrumentenklänge kommen von {sf}, © 2000–2019 Frank&nbsp;Wen, Michael&nbsp;Cowgill und S.&nbsp;Christian&nbsp;Collins, genutzt unter der MIT-Lizenz.",
 "h_notdo": "Was die App nicht tut",
 "p_notdo": "Sie erhebt keine Daten, zeigt keine Werbung, enthält weder Chat noch soziale Funktion und stellt von sich aus keine Netzwerkanfrage. Einzelheiten in der {privacy}.",
 "privacy": "Datenschutzerklärung",
 "h_warranty": "Keine Gewährleistung",
 "p_warranty": "Die App wird wie besehen bereitgestellt. Soweit gesetzlich zulässig und ohne Ihre Rechte aus Apples Standard-EULA oder aus zwingendem Verbraucherrecht Ihres Landes einzuschränken, wird nicht zugesichert, dass sie unterbrechungs- oder fehlerfrei läuft.",
 "h_changes": "Änderungen",
 "p_changes": "Diese Bedingungen können sich mit einer neuen Version der App ändern. Das Datum oben ändert sich mit ihnen, und eine wesentliche Änderung wird in den Versionshinweisen beschrieben.",
 "h_contact": "Kontakt",
 "governing": "Dies ist eine Übersetzung. Maßgeblich ist im Zweifel die englische Fassung: {link}.",
},
"fr": {
 "title": "Conditions d’utilisation", "meta": "Conditions d’utilisation de l’app iOS TappyMusic.",
 "h": "Conditions d’utilisation",
 "updated": "Dernière mise à jour le 2&nbsp;août&nbsp;2026.",
 "p_eula": "TappyMusic est concédée sous licence, non vendue, au titre du {eula} d’Apple, qui s’applique intégralement. Les conditions ci-dessous s’y ajoutent et décrivent le comportement de cette app en particulier.",
 "eula": "Contrat de licence utilisateur final standard",
 "h_purchases": "Achats",
 "p_purchases": "Les packs de mélodies, l’import de vos morceaux, la création de vos cliparts et TappyMusic&nbsp;Pro sont des <strong>achats uniques</strong>. Il n’y a pas d’abonnement et rien ne se renouvelle. Chaque achat est partageable en famille et donc disponible pour votre groupe Partage familial Apple.",
 "p_refunds": "Les achats sont traités par Apple. Les remboursements relèvent d’Apple, via {refund}. Si un achat est remboursé ou si un membre de la famille cesse de le partager, l’app revient à l’état non acheté pour cet élément — le pack gratuit et la mélodie d’essai de chaque pack payant continuent de fonctionner.",
 "p_pro": "TappyMusic&nbsp;Pro comprend tout ce que l’app vend : tous les packs de mélodies, l’import de vos morceaux et la création de vos cliparts. Ces trois éléments sont aussi vendus séparément ; acheter Pro après l’un d’eux ne rembourse pas l’achat antérieur, c’est pourquoi la boutique montre ce que vous possédez déjà.",
 "h_content": "Le contenu que vous apportez",
 "p_content": "Vous pouvez importer des fichiers MIDI. Ces fichiers, et les morceaux qui en sont issus, restent sur votre appareil et ne sont envoyés nulle part. Il vous appartient de disposer du droit d’utiliser chaque fichier importé. TappyMusic ne revendique aucune propriété sur vos morceaux importés et ne vous accorde aucun droit sur la musique d’autrui.",
 "h_music": "La musique fournie avec l’app",
 "p_music": "Chaque mélodie incluse dans TappyMusic est une composition du domaine public. Les arrangements et les enregistrements par synthèse sont les nôtres. Les sons d’instruments proviennent de {sf}, © 2000–2019 Frank&nbsp;Wen, Michael&nbsp;Cowgill et S.&nbsp;Christian&nbsp;Collins, utilisés sous licence MIT.",
 "h_notdo": "Ce que l’app ne fait pas",
 "p_notdo": "Elle ne collecte aucune donnée, n’affiche aucune publicité, ne contient ni discussion ni fonction sociale, et n’émet aucune requête réseau de sa propre initiative. Voir la {privacy} pour le détail.",
 "privacy": "politique de confidentialité",
 "h_warranty": "Absence de garantie",
 "p_warranty": "L’app est fournie en l’état. Dans la mesure permise par la loi, et sans limiter les droits que vous tenez de l’EULA standard d’Apple ou du droit impératif de la consommation de votre pays, aucune garantie n’est donnée quant à un fonctionnement ininterrompu ou exempt d’erreurs.",
 "h_changes": "Modifications",
 "p_changes": "Ces conditions peuvent changer avec une nouvelle version de l’app. La date ci-dessus change avec elles, et toute modification substantielle sera décrite dans les notes de version.",
 "h_contact": "Contact",
 "governing": "Ceci est une traduction. En cas de divergence, la version anglaise fait foi : {link}.",
},
"es": {
 "title": "Condiciones de uso", "meta": "Condiciones de uso de la app de iOS TappyMusic.",
 "h": "Condiciones de uso",
 "updated": "Última actualización: 2&nbsp;de&nbsp;agosto&nbsp;de&nbsp;2026.",
 "p_eula": "TappyMusic se licencia, no se vende, con arreglo al {eula} de Apple, que se aplica íntegramente. Las condiciones siguientes lo complementan y describen cómo se comporta esta app en concreto.",
 "eula": "Contrato de licencia de usuario final estándar",
 "h_purchases": "Compras",
 "p_purchases": "Los packs de melodías, importar tus canciones, crear tus cliparts y TappyMusic&nbsp;Pro son <strong>compras únicas</strong>. No hay suscripción y nada se renueva. Todas las compras se comparten en familia, así que están disponibles para tu grupo de En familia de Apple.",
 "p_refunds": "Las compras las procesa Apple. Los reembolsos los concede Apple, a través de {refund}. Si se reembolsa una compra o un familiar deja de compartirla, la app vuelve al estado sin comprar para ese elemento: el pack gratuito y la melodía de muestra de cada pack de pago siguen funcionando.",
 "p_pro": "TappyMusic&nbsp;Pro incluye todo lo que vende la app: todos los packs de melodías, importar tus canciones y crear tus cliparts. Esas tres cosas también se venden por separado; comprar Pro después de una de ellas no reembolsa la compra anterior, así que la tienda muestra lo que ya tienes.",
 "h_content": "El contenido que traes tú",
 "p_content": "Puedes importar archivos MIDI. Esos archivos, y las canciones hechas con ellos, se quedan en tu dispositivo y no se suben a ningún sitio. Eres responsable de tener derecho a usar cualquier archivo que importes. TappyMusic no reclama la propiedad de tus canciones importadas ni te concede derecho alguno sobre la música de otras personas.",
 "h_music": "La música que viene con la app",
 "p_music": "Todas las melodías incluidas en TappyMusic son composiciones de dominio público. Los arreglos y las grabaciones por síntesis son nuestros. Los sonidos de los instrumentos proceden de {sf}, © 2000–2019 Frank&nbsp;Wen, Michael&nbsp;Cowgill y S.&nbsp;Christian&nbsp;Collins, usados bajo licencia MIT.",
 "h_notdo": "Lo que la app no hace",
 "p_notdo": "No recoge datos, no muestra publicidad, no tiene chat ni función social, y no hace ninguna petición de red por su cuenta. Consulta la {privacy} para el detalle.",
 "privacy": "política de privacidad",
 "h_warranty": "Sin garantía",
 "p_warranty": "La app se ofrece tal cual. En la medida en que lo permita la ley, y sin limitar los derechos que te correspondan por el EULA estándar de Apple o por la normativa imperativa de consumo de tu país, no se garantiza que funcione sin interrupciones ni errores.",
 "h_changes": "Cambios",
 "p_changes": "Estas condiciones pueden cambiar con una versión nueva de la app. La fecha de arriba cambia con ellas, y un cambio sustancial se describirá en las notas de esa versión.",
 "h_contact": "Contacto",
 "governing": "Esto es una traducción. En caso de discrepancia, prevalece la versión en inglés: {link}.",
},
"it": {
 "title": "Condizioni d’uso", "meta": "Condizioni d’uso dell’app iOS TappyMusic.",
 "h": "Condizioni d’uso",
 "updated": "Ultimo aggiornamento: 2&nbsp;agosto&nbsp;2026.",
 "p_eula": "TappyMusic è concessa in licenza, non venduta, ai sensi del {eula} di Apple, che si applica integralmente. Le condizioni qui sotto lo integrano e descrivono il comportamento di questa app.",
 "eula": "Contratto di licenza con l’utente finale standard",
 "h_purchases": "Acquisti",
 "p_purchases": "I pacchetti di melodie, l’importazione dei tuoi brani, la creazione dei tuoi clipart e TappyMusic&nbsp;Pro sono <strong>acquisti una tantum</strong>. Non c’è alcun abbonamento e nulla si rinnova. Ogni acquisto è condivisibile in famiglia, quindi è disponibile per il tuo gruppo In famiglia di Apple.",
 "p_refunds": "Gli acquisti sono elaborati da Apple. I rimborsi spettano ad Apple, tramite {refund}. Se un acquisto viene rimborsato o un familiare smette di condividerlo, l’app torna allo stato non acquistato per quell’elemento: il pacchetto gratuito e la melodia di prova di ogni pacchetto a pagamento continuano a funzionare.",
 "p_pro": "TappyMusic&nbsp;Pro comprende tutto ciò che l’app vende: ogni pacchetto di melodie, l’importazione dei tuoi brani e la creazione dei tuoi clipart. Questi tre sono venduti anche separatamente; acquistare Pro dopo uno di essi non rimborsa l’acquisto precedente, perciò il negozio mostra ciò che possiedi già.",
 "h_content": "I contenuti che porti tu",
 "p_content": "Puoi importare file MIDI. Quei file, e i brani che ne derivano, restano sul tuo dispositivo e non vengono caricati da nessuna parte. Sei responsabile di avere il diritto di usare ogni file che importi. TappyMusic non rivendica alcuna proprietà sui tuoi brani importati e non ti concede alcun diritto sulla musica altrui.",
 "h_music": "La musica inclusa nell’app",
 "p_music": "Ogni melodia inclusa in TappyMusic è una composizione di pubblico dominio. Gli arrangiamenti e le registrazioni per sintesi sono nostri. I suoni degli strumenti provengono da {sf}, © 2000–2019 Frank&nbsp;Wen, Michael&nbsp;Cowgill e S.&nbsp;Christian&nbsp;Collins, usati con licenza MIT.",
 "h_notdo": "Cosa l’app non fa",
 "p_notdo": "Non raccoglie dati, non mostra pubblicità, non contiene chat né funzioni social e non effettua richieste di rete di propria iniziativa. Vedi l’{privacy} per i dettagli.",
 "privacy": "informativa sulla privacy",
 "h_warranty": "Nessuna garanzia",
 "p_warranty": "L’app è fornita così com’è. Nei limiti consentiti dalla legge, e senza limitare i diritti che ti spettano in base all’EULA standard di Apple o alla normativa imperativa a tutela dei consumatori del tuo Paese, non si garantisce che funzioni senza interruzioni o errori.",
 "h_changes": "Modifiche",
 "p_changes": "Queste condizioni possono cambiare con una nuova versione dell’app. La data qui sopra cambia con esse, e una modifica sostanziale sarà descritta nelle note di quella versione.",
 "h_contact": "Contatti",
 "governing": "Questa è una traduzione. In caso di difformità prevale la versione inglese: {link}.",
},
"pt": {
 "title": "Termos de Uso", "meta": "Termos de uso do app iOS TappyMusic.",
 "h": "Termos de Uso",
 "updated": "Última atualização: 2&nbsp;de&nbsp;agosto&nbsp;de&nbsp;2026.",
 "p_eula": "O TappyMusic é licenciado, não vendido, nos termos do {eula} da Apple, que se aplica integralmente. Os termos abaixo o complementam e descrevem como este app se comporta.",
 "eula": "Contrato de Licença de Usuário Final Padrão",
 "h_purchases": "Compras",
 "p_purchases": "Pacotes de melodias, importar suas músicas, criar seus cliparts e o TappyMusic&nbsp;Pro são <strong>compras únicas</strong>. Não há assinatura e nada se renova. Toda compra é compartilhável com a família, portanto fica disponível para o seu grupo do Compartilhamento Familiar da Apple.",
 "p_refunds": "As compras são processadas pela Apple. Os reembolsos cabem à Apple, por meio de {refund}. Se uma compra for reembolsada ou um familiar deixar de compartilhá-la, o app volta ao estado não comprado para aquele item — o pacote gratuito e a melodia de amostra de cada pacote pago continuam funcionando.",
 "p_pro": "O TappyMusic&nbsp;Pro inclui tudo o que o app vende: todos os pacotes de melodias, importar suas músicas e criar seus cliparts. Esses três também são vendidos separadamente; comprar o Pro depois de um deles não reembolsa a compra anterior, por isso a loja mostra o que você já tem.",
 "h_content": "O conteúdo que você traz",
 "p_content": "Você pode importar arquivos MIDI. Esses arquivos, e as músicas feitas a partir deles, ficam no seu aparelho e não são enviados a lugar algum. É sua a responsabilidade de ter o direito de usar cada arquivo que importar. O TappyMusic não reivindica propriedade sobre as suas músicas importadas e não lhe concede direito algum sobre a música de terceiros.",
 "h_music": "A música que vem com o app",
 "p_music": "Toda melodia incluída no TappyMusic é uma composição em domínio público. Os arranjos e as gravações por síntese são nossos. Os sons dos instrumentos vêm do {sf}, © 2000–2019 Frank&nbsp;Wen, Michael&nbsp;Cowgill e S.&nbsp;Christian&nbsp;Collins, usados sob a licença MIT.",
 "h_notdo": "O que o app não faz",
 "p_notdo": "Ele não coleta dados, não exibe publicidade, não tem bate-papo nem função social e não faz nenhuma requisição de rede por conta própria. Veja a {privacy} para os detalhes.",
 "privacy": "política de privacidade",
 "h_warranty": "Sem garantia",
 "p_warranty": "O app é fornecido no estado em que se encontra. Na medida permitida por lei, e sem limitar os direitos que você tenha pelo EULA padrão da Apple ou pela legislação consumerista cogente do seu país, não se garante que ele funcionará sem interrupções ou erros.",
 "h_changes": "Alterações",
 "p_changes": "Estes termos podem mudar com uma nova versão do app. A data acima muda junto, e uma alteração relevante será descrita nas notas dessa versão.",
 "h_contact": "Contato",
 "governing": "Esta é uma tradução. Em caso de divergência, prevalece a versão em inglês: {link}.",
},
"ja": {
 "title": "利用規約", "meta": "iOS アプリ TappyMusic の利用規約。",
 "h": "利用規約",
 "updated": "最終更新：2026年8月2日。",
 "p_eula": "TappyMusic は販売ではなく、Apple の{eula}に基づいて使用を許諾されます。同契約はそのすべてが適用されます。以下の条項はそれに追加されるもので、本アプリ固有の動作を説明します。",
 "eula": "標準エンドユーザー使用許諾契約",
 "h_purchases": "購入について",
 "p_purchases": "曲パック、自分の曲の取りこみ、自分のクリップアート作り、TappyMusic&nbsp;Pro は、いずれも<strong>買い切り</strong>です。サブスクリプションはなく、自動更新もありません。すべての購入はファミリー共有に対応しており、Apple のファミリー共有グループでご利用いただけます。",
 "p_refunds": "購入の処理は Apple が行います。返金の可否は Apple が判断し、{refund}から手続きします。返金された場合、またはご家族が共有をやめた場合、その項目についてアプリは未購入の状態に戻ります——無料パックと、各有料パックの無料お試し曲は引き続き使えます。",
 "p_pro": "TappyMusic&nbsp;Pro には、アプリが販売するものがすべて含まれます。すべての曲パック、自分の曲の取りこみ、自分のクリップアート作りです。この3つは個別にも販売しています。いずれかを買ったあとに Pro を購入しても先の購入は返金されないため、ショップには購入済みのものが表示されます。",
 "h_content": "お客様が持ちこむ内容",
 "p_content": "MIDI ファイルを取りこめます。そのファイルと、そこから作られた曲は端末に残り、どこにもアップロードされません。取りこむファイルを使用する権利をお持ちであることは、お客様の責任となります。TappyMusic は取りこまれた曲について所有権を主張せず、また他者の音楽に関するいかなる権利もお客様に付与しません。",
 "h_music": "アプリに収録されている音楽",
 "p_music": "TappyMusic に収録されたメロディーは、すべてパブリックドメインの楽曲です。編曲および合成による録音は当方に帰属します。楽器音は {sf}（© 2000–2019 Frank&nbsp;Wen、Michael&nbsp;Cowgill、S.&nbsp;Christian&nbsp;Collins）を MIT ライセンスのもとで使用しています。",
 "h_notdo": "アプリが行わないこと",
 "p_notdo": "データを収集せず、広告を表示せず、チャットやソーシャル機能を持たず、自ら通信を行うこともありません。詳しくは{privacy}をご覧ください。",
 "privacy": "プライバシーポリシー",
 "h_warranty": "無保証",
 "p_warranty": "本アプリは現状有姿で提供されます。法令の許す範囲で、また Apple の標準 EULA やお住まいの国の強行的な消費者法に基づくお客様の権利を制限することなく、中断や不具合がないことは保証されません。",
 "h_changes": "変更について",
 "p_changes": "本規約はアプリの新しいバージョンとともに変更されることがあります。その際は上記の日付も変わり、重要な変更はそのバージョンのリリースノートに記載されます。",
 "h_contact": "お問い合わせ",
 "governing": "これは翻訳です。相違がある場合は英語版が優先します：{link}。",
},
"ko": {
 "title": "이용약관", "meta": "iOS 앱 TappyMusic의 이용약관.",
 "h": "이용약관",
 "updated": "최종 갱신: 2026년 8월 2일.",
 "p_eula": "TappyMusic은 판매되는 것이 아니라 Apple의 {eula}에 따라 사용이 허락됩니다. 해당 계약은 전부 적용됩니다. 아래 조항은 그에 더해지는 것으로, 이 앱이 어떻게 동작하는지를 설명합니다.",
 "eula": "표준 최종 사용자 사용권 계약",
 "h_purchases": "구입",
 "p_purchases": "멜로디 팩, 내 곡 가져오기, 나만의 클립아트 만들기, TappyMusic&nbsp;Pro는 모두 <strong>한 번만 구입하는 항목</strong>입니다. 구독은 없고 자동 갱신도 없습니다. 모든 구입은 가족 공유가 되므로 Apple 가족 공유 그룹에서 함께 쓸 수 있습니다.",
 "p_refunds": "구입은 Apple이 처리합니다. 환불 여부는 Apple이 결정하며 {refund}를 통해 신청합니다. 환불되거나 가족 구성원이 공유를 중단하면 해당 항목에 대해 앱은 미구입 상태로 돌아갑니다 — 무료 팩과 각 유료 팩의 무료 미리듣기 곡은 계속 작동합니다.",
 "p_pro": "TappyMusic&nbsp;Pro에는 앱이 판매하는 모든 것이 들어 있습니다. 모든 멜로디 팩, 내 곡 가져오기, 나만의 클립아트 만들기입니다. 이 세 가지는 개별로도 판매합니다. 그중 하나를 산 뒤에 Pro를 사도 먼저 한 구입은 환불되지 않으므로, 상점은 이미 보유한 것을 표시합니다.",
 "h_content": "직접 가져오는 콘텐츠",
 "p_content": "MIDI 파일을 가져올 수 있습니다. 그 파일과 그것으로 만든 곡은 기기에 남고 어디에도 업로드되지 않습니다. 가져오는 파일을 사용할 권리가 있는지는 사용자의 책임입니다. TappyMusic은 가져온 곡에 대해 소유권을 주장하지 않으며, 타인의 음악에 대한 어떠한 권리도 부여하지 않습니다.",
 "h_music": "앱에 함께 담긴 음악",
 "p_music": "TappyMusic에 담긴 모든 멜로디는 퍼블릭 도메인 작품입니다. 편곡과 합성 녹음은 저희의 것입니다. 악기 소리는 {sf}(© 2000–2019 Frank&nbsp;Wen, Michael&nbsp;Cowgill, S.&nbsp;Christian&nbsp;Collins)에서 가져와 MIT 라이선스로 사용합니다.",
 "h_notdo": "앱이 하지 않는 일",
 "p_notdo": "데이터를 수집하지 않고, 광고를 보여주지 않으며, 채팅이나 소셜 기능이 없고, 스스로 네트워크 요청을 하지 않습니다. 자세한 내용은 {privacy}을 보세요.",
 "privacy": "개인정보 처리방침",
 "h_warranty": "보증 없음",
 "p_warranty": "앱은 있는 그대로 제공됩니다. 법이 허용하는 범위에서, 그리고 Apple의 표준 EULA나 거주 국가의 강행 소비자법에 따른 권리를 제한하지 않으면서, 중단이나 오류가 없으리라는 보증은 하지 않습니다.",
 "h_changes": "변경",
 "p_changes": "이 약관은 앱의 새 버전과 함께 바뀔 수 있습니다. 위의 날짜도 함께 바뀌며, 중요한 변경은 그 버전의 릴리스 노트에 설명됩니다.",
 "h_contact": "문의",
 "governing": "이 문서는 번역본입니다. 내용이 다를 경우 영어판이 우선합니다: {link}.",
},
"el": {
 "title": "Όροι χρήσης", "meta": "Όροι χρήσης της εφαρμογής iOS TappyMusic.",
 "h": "Όροι χρήσης",
 "updated": "Τελευταία ενημέρωση: 2&nbsp;Αυγούστου&nbsp;2026.",
 "p_eula": "Το TappyMusic παραχωρείται με άδεια, δεν πωλείται, βάσει της {eula} της Apple, η οποία ισχύει πλήρως. Οι παρακάτω όροι την συμπληρώνουν και περιγράφουν πώς συμπεριφέρεται αυτή η εφαρμογή.",
 "eula": "Τυπικής Άδειας Χρήσης Τελικού Χρήστη",
 "h_purchases": "Αγορές",
 "p_purchases": "Τα πακέτα μελωδιών, η εισαγωγή των τραγουδιών σου, η δημιουργία κλιπάρτ και το TappyMusic&nbsp;Pro είναι <strong>εφάπαξ αγορές</strong>. Δεν υπάρχει συνδρομή και τίποτα δεν ανανεώνεται. Κάθε αγορά μοιράζεται με την οικογένεια, άρα είναι διαθέσιμη στην ομάδα Οικογενειακής Κοινής Χρήσης της Apple.",
 "p_refunds": "Οι αγορές επεξεργάζονται από την Apple. Οι επιστροφές χρημάτων εναπόκεινται στην Apple, μέσω {refund}. Αν μια αγορά επιστραφεί ή αν ένα μέλος της οικογένειας πάψει να τη μοιράζεται, η εφαρμογή επιστρέφει στην κατάσταση «μη αγορασμένο» για εκείνο το στοιχείο — το δωρεάν πακέτο και η δωρεάν μελωδία κάθε πακέτου επί πληρωμή συνεχίζουν να λειτουργούν.",
 "p_pro": "Το TappyMusic&nbsp;Pro περιλαμβάνει όλα όσα πουλά η εφαρμογή: κάθε πακέτο μελωδιών, την εισαγωγή των τραγουδιών σου και τη δημιουργία κλιπάρτ. Αυτά τα τρία πωλούνται και ξεχωριστά· αν αγοράσεις το Pro μετά από ένα από αυτά, η προηγούμενη αγορά δεν επιστρέφεται — γι' αυτό το κατάστημα δείχνει τι ήδη έχεις.",
 "h_content": "Το περιεχόμενο που φέρνεις εσύ",
 "p_content": "Μπορείς να εισάγεις αρχεία MIDI. Τα αρχεία αυτά, και τα τραγούδια που προκύπτουν, μένουν στη συσκευή σου και δεν ανεβαίνουν πουθενά. Είναι δική σου ευθύνη να έχεις το δικαίωμα χρήσης κάθε αρχείου που εισάγεις. Το TappyMusic δεν διεκδικεί κυριότητα στα τραγούδια που εισάγεις και δεν σου παραχωρεί κανένα δικαίωμα στη μουσική τρίτων.",
 "h_music": "Η μουσική που έρχεται με την εφαρμογή",
 "p_music": "Κάθε μελωδία στο TappyMusic είναι σύνθεση δημόσιας κτήσης. Οι ενορχηστρώσεις και οι ηχογραφήσεις μέσω σύνθεσης είναι δικές μας. Οι ήχοι των οργάνων προέρχονται από το {sf}, © 2000–2019 Frank&nbsp;Wen, Michael&nbsp;Cowgill και S.&nbsp;Christian&nbsp;Collins, με άδεια MIT.",
 "h_notdo": "Τι δεν κάνει η εφαρμογή",
 "p_notdo": "Δεν συλλέγει δεδομένα, δεν δείχνει διαφημίσεις, δεν έχει συνομιλία ούτε κοινωνικές λειτουργίες, και δεν κάνει από μόνη της καμία αίτηση δικτύου. Δες την {privacy} για τις λεπτομέρειες.",
 "privacy": "πολιτική απορρήτου",
 "h_warranty": "Καμία εγγύηση",
 "p_warranty": "Η εφαρμογή παρέχεται ως έχει. Στον βαθμό που επιτρέπει ο νόμος, και χωρίς να περιορίζονται τα δικαιώματά σου από την Τυπική Άδεια της Apple ή από την αναγκαστικού δικαίου νομοθεσία προστασίας καταναλωτή της χώρας σου, δεν δίνεται εγγύηση ότι θα λειτουργεί αδιάλειπτα ή χωρίς σφάλματα.",
 "h_changes": "Αλλαγές",
 "p_changes": "Οι όροι αυτοί μπορεί να αλλάξουν με νέα έκδοση της εφαρμογής. Η παραπάνω ημερομηνία αλλάζει μαζί τους, και κάθε ουσιώδης αλλαγή θα περιγράφεται στις σημειώσεις εκείνης της έκδοσης.",
 "h_contact": "Επικοινωνία",
 "governing": "Αυτή είναι μετάφραση. Σε περίπτωση απόκλισης υπερισχύει η αγγλική έκδοση: {link}.",
},
"uk": {
 "title": "Умови користування", "meta": "Умови користування застосунком TappyMusic для iOS.",
 "h": "Умови користування",
 "updated": "Востаннє оновлено 2&nbsp;серпня&nbsp;2026&nbsp;року.",
 "p_eula": "TappyMusic ліцензується, а не продається, згідно з {eula} Apple, яка застосовується в повному обсязі. Наведені нижче умови доповнюють її та описують, як поводиться саме цей застосунок.",
 "eula": "Стандартною ліцензійною угодою кінцевого користувача",
 "h_purchases": "Покупки",
 "p_purchases": "Набори мелодій, імпорт власних пісень, створення власних кліпартів і TappyMusic&nbsp;Pro — це <strong>одноразові покупки</strong>. Підписки немає, і ніщо не поновлюється. Кожна покупка доступна в межах сімейного доступу, тобто всій вашій сімейній групі Apple.",
 "p_refunds": "Покупки обробляє Apple. Рішення про повернення коштів ухвалює Apple через {refund}. Якщо покупку повернуто або хтось із родини припинив ділитися нею, застосунок повертається до стану «не куплено» для цього елемента — безкоштовний набір і безкоштовна ознайомлювальна мелодія кожного платного набору працюють далі.",
 "p_pro": "TappyMusic&nbsp;Pro містить усе, що продає застосунок: усі набори мелодій, імпорт власних пісень і створення власних кліпартів. Ці три речі продаються й окремо; купівля Pro після однієї з них не повертає коштів за попередню покупку, тому магазин показує, що вам уже належить.",
 "h_content": "Вміст, який ви приносите",
 "p_content": "Ви можете імпортувати файли MIDI. Ці файли й пісні, зроблені з них, лишаються на вашому пристрої й нікуди не завантажуються. Ви відповідаєте за наявність права використовувати кожен імпортований файл. TappyMusic не претендує на власність щодо ваших імпортованих пісень і не надає вам жодних прав на чужу музику.",
 "h_music": "Музика, що йде із застосунком",
 "p_music": "Кожна мелодія в TappyMusic — це твір, що є суспільним надбанням. Аранжування та синтезовані записи належать нам. Звуки інструментів походять із {sf}, © 2000–2019 Frank&nbsp;Wen, Michael&nbsp;Cowgill і S.&nbsp;Christian&nbsp;Collins, використані за ліцензією MIT.",
 "h_notdo": "Чого застосунок не робить",
 "p_notdo": "Він не збирає даних, не показує реклами, не має ні чату, ні соціальних функцій і не робить жодного мережевого запиту з власної ініціативи. Подробиці — у {privacy}.",
 "privacy": "політиці приватності",
 "h_warranty": "Без гарантій",
 "p_warranty": "Застосунок надається як є. У межах, дозволених законом, і не обмежуючи ваших прав за стандартною ліцензійною угодою Apple чи за імперативним споживчим правом вашої країни, не надається гарантії, що він працюватиме безперервно або без помилок.",
 "h_changes": "Зміни",
 "p_changes": "Ці умови можуть змінитися з новою версією застосунку. Дата вгорі змінюється разом з ними, а суттєву зміну буде описано в примітках до випуску тієї версії.",
 "h_contact": "Контакти",
 "governing": "Це переклад. У разі розбіжностей чинною є англійська версія: {link}.",
},
"ru": {
 "title": "Условия использования", "meta": "Условия использования приложения TappyMusic для iOS.",
 "h": "Условия использования",
 "updated": "Последнее обновление: 2&nbsp;августа&nbsp;2026&nbsp;года.",
 "p_eula": "TappyMusic лицензируется, а не продаётся, в соответствии со {eula} Apple, которое применяется в полном объёме. Приведённые ниже условия дополняют его и описывают, как ведёт себя именно это приложение.",
 "eula": "Стандартным лицензионным соглашением с конечным пользователем",
 "h_purchases": "Покупки",
 "p_purchases": "Наборы мелодий, импорт своих песен, создание своих клипартов и TappyMusic&nbsp;Pro — это <strong>разовые покупки</strong>. Подписки нет, и ничто не продлевается. Каждая покупка доступна в рамках семейного доступа, то есть всей вашей семейной группе Apple.",
 "p_refunds": "Покупки обрабатывает Apple. Решение о возврате средств принимает Apple, через {refund}. Если покупка возвращена или кто-то из родных перестал ею делиться, приложение возвращается к состоянию «не куплено» для этого элемента — бесплатный набор и бесплатная ознакомительная мелодия каждого платного набора продолжают работать.",
 "p_pro": "TappyMusic&nbsp;Pro включает всё, что продаёт приложение: все наборы мелодий, импорт своих песен и создание своих клипартов. Эти три вещи продаются и по отдельности; покупка Pro после одной из них не возвращает средств за предыдущую покупку, поэтому магазин показывает, что у вас уже есть.",
 "h_content": "Содержимое, которое приносите вы",
 "p_content": "Вы можете импортировать файлы MIDI. Эти файлы и сделанные из них песни остаются на вашем устройстве и никуда не выгружаются. Вы отвечаете за наличие права использовать каждый импортируемый файл. TappyMusic не претендует на собственность в отношении ваших импортированных песен и не предоставляет вам никаких прав на чужую музыку.",
 "h_music": "Музыка, которая идёт с приложением",
 "p_music": "Каждая мелодия в TappyMusic — произведение, являющееся общественным достоянием. Аранжировки и синтезированные записи принадлежат нам. Звуки инструментов взяты из {sf}, © 2000–2019 Frank&nbsp;Wen, Michael&nbsp;Cowgill и S.&nbsp;Christian&nbsp;Collins, использованы по лицензии MIT.",
 "h_notdo": "Чего приложение не делает",
 "p_notdo": "Оно не собирает данных, не показывает рекламы, не имеет ни чата, ни социальных функций и не делает ни одного сетевого запроса по собственной инициативе. Подробности — в {privacy}.",
 "privacy": "политике приватности",
 "h_warranty": "Без гарантий",
 "p_warranty": "Приложение предоставляется как есть. В пределах, допускаемых законом, и не ограничивая ваших прав по стандартному лицензионному соглашению Apple или по императивному потребительскому праву вашей страны, не даётся гарантии, что оно будет работать непрерывно или без ошибок.",
 "h_changes": "Изменения",
 "p_changes": "Эти условия могут измениться с новой версией приложения. Дата выше меняется вместе с ними, а существенное изменение будет описано в примечаниях к выпуску той версии.",
 "h_contact": "Контакты",
 "governing": "Это перевод. При расхождениях действует английская версия: {link}.",
},
}
