"""STARTING POINT — copy into your app and rewrite the keys listed below.

This is a real shipped privacy policy, in eleven languages, for an app that
collects nothing. If that is true of your app too, most of this is already
right. If it is not true, this file is a lie in eleven languages, so read it.

REWRITE FOR YOUR APP, in every language:

    list             what actually stays on the device
    p_purchases      the names of what you sell, or drop the section
    p_family         only if your purchases are not Family Shareable
    p_children       the age rating, and anything a child can create
    p_api            your PrivacyInfo.xcprivacy declarations, verbatim
    p_site           only if you do not host on GitHub Pages

CHECK, do not assume:

    note             "collects nothing" — is that still true after analytics?
    updated          the date, in each language's convention

Keys the renderer needs are documented in make_site_legal.py in the template.
"""

PRIVACY = {
"en": {
 "title": "Privacy Policy", "meta": "TappyMusic collects nothing. No analytics, no tracking, no accounts, and no data leaves the device.",
 "h": "Privacy Policy",
 "updated": "Last updated 2&nbsp;August&nbsp;2026. Applies to the TappyMusic iOS app and this website.",
 "note": "<strong>TappyMusic collects nothing.</strong> There is no analytics SDK, no crash reporter, no advertising, no tracking, and no account. The app makes no network request of its own — the only server it ever talks to is Apple's App&nbsp;Store, and only when you buy or restore something.",
 "h_device": "What stays on your device",
 "p_device": "Everything. Specifically:",
 "list": [
  "Which songs you have played and where you left off",
  "Songs you import from MIDI files, and the cliparts you make",
  "Your settings — instrument, tempo, which packs are on the shelf, whether the learning aids are on",
  "Backups you choose to save, which are ordinary zip files written wherever you put them",
 ],
 "p_device_after": "None of it is uploaded anywhere. Deleting the app deletes all of it, which is why the app offers a backup you control.",
 "h_purchases": "Purchases",
 "p_purchases": "Melody packs, importing, cliparts and TappyMusic&nbsp;Pro are one-time purchases handled entirely by Apple. We never see your payment details, your Apple Account, or your name. The app asks Apple what you own and stores the answer on the device so that what you bought keeps working offline.",
 "p_family": "Purchases are Family Shareable. If a member of your family group shares a purchase with you, Apple tells the app that you are entitled to it — and nothing about who that person is.",
 "h_children": "Children",
 "p_children": "The app is designed for children and is rated 4+. It collects no personal information from anyone, of any age. There is no chat, no user-generated content that is shared, no social feature, no web browser and no advertising. Cliparts a child builds from emoji stay on that device.",
 "h_api": "Required-reason APIs",
 "p_api": "Apple requires apps to declare certain APIs and why they are used. TappyMusic declares exactly one: <code>UserDefaults</code>, under reason <code>CA92.1</code> — storing your own settings on your own device. The declaration ships in the app as <code>PrivacyInfo.xcprivacy</code>, and its collected-data list is empty.",
 "h_site": "This website",
 "p_site": "These pages are static files served by GitHub&nbsp;Pages. They set no cookies, embed no scripts, load no fonts or images from anywhere else, and run no analytics. GitHub may log requests to its servers as part of operating the service; see {github}.",
 "github": "GitHub's privacy statement",
 "h_changes": "Changes",
 "p_changes": "If this policy ever changes, the date at the top changes with it. A change that reduced your privacy would come with a new version of the app, and would be described in that version's release notes.",
 "h_contact": "Contact",
 "p_contact": "Questions about this policy, or about what the app does with anything: {support}.",
 "support": "get in touch",
 "governing": "",
},
"de": {
 "title": "Datenschutzerklärung", "meta": "TappyMusic erhebt nichts. Keine Analyse, kein Tracking, keine Konten, und keine Daten verlassen das Gerät.",
 "h": "Datenschutzerklärung",
 "updated": "Zuletzt aktualisiert am 2.&nbsp;August&nbsp;2026. Gilt für die iOS-App TappyMusic und für diese Website.",
 "note": "<strong>TappyMusic erhebt nichts.</strong> Es gibt kein Analyse-SDK, keinen Absturzberichter, keine Werbung, kein Tracking und kein Konto. Die App stellt von sich aus keine Netzwerkanfrage — der einzige Server, mit dem sie je spricht, ist Apples App&nbsp;Store, und das nur beim Kaufen oder Wiederherstellen.",
 "h_device": "Was auf Ihrem Gerät bleibt",
 "p_device": "Alles. Im Einzelnen:",
 "list": [
  "Welche Lieder gespielt wurden und wo Sie aufgehört haben",
  "Lieder, die Sie aus MIDI-Dateien importieren, und die Cliparts, die Sie machen",
  "Ihre Einstellungen — Instrument, Tempo, welche Pakete im Regal stehen, ob die Lernhilfen an sind",
  "Backups, die Sie selbst speichern: gewöhnliche ZIP-Dateien, geschrieben dorthin, wo Sie sie ablegen",
 ],
 "p_device_after": "Nichts davon wird irgendwohin hochgeladen. Wird die App gelöscht, ist alles davon weg — deshalb bietet die App ein Backup an, über das Sie bestimmen.",
 "h_purchases": "Käufe",
 "p_purchases": "Melodiepakete, Import, Cliparts und TappyMusic&nbsp;Pro sind einmalige Käufe, die vollständig von Apple abgewickelt werden. Wir sehen weder Ihre Zahlungsdaten noch Ihren Apple-Account noch Ihren Namen. Die App fragt Apple, was Ihnen gehört, und speichert die Antwort auf dem Gerät, damit Gekauftes auch offline weiter funktioniert.",
 "p_family": "Käufe sind über die Familienfreigabe teilbar. Teilt jemand aus Ihrer Familiengruppe einen Kauf mit Ihnen, teilt Apple der App mit, dass Sie berechtigt sind — und nichts darüber, wer diese Person ist.",
 "h_children": "Kinder",
 "p_children": "Die App ist für Kinder gemacht und mit 4+ eingestuft. Sie erhebt von niemandem personenbezogene Daten, in keinem Alter. Es gibt keinen Chat, keine geteilten nutzergenerierten Inhalte, keine soziale Funktion, keinen Webbrowser und keine Werbung. Cliparts, die ein Kind aus Emoji baut, bleiben auf diesem Gerät.",
 "h_api": "APIs mit Begründungspflicht",
 "p_api": "Apple verlangt, bestimmte APIs und ihren Verwendungszweck anzugeben. TappyMusic gibt genau eine an: <code>UserDefaults</code> mit dem Grund <code>CA92.1</code> — das Speichern Ihrer eigenen Einstellungen auf Ihrem eigenen Gerät. Die Angabe liegt der App als <code>PrivacyInfo.xcprivacy</code> bei, und ihre Liste erhobener Daten ist leer.",
 "h_site": "Diese Website",
 "p_site": "Diese Seiten sind statische Dateien, ausgeliefert von GitHub&nbsp;Pages. Sie setzen keine Cookies, binden keine Skripte ein, laden weder Schriften noch Bilder von anderswo und führen keine Analyse aus. GitHub kann Anfragen an seine Server im Rahmen des Betriebs protokollieren; siehe {github}.",
 "github": "GitHubs Datenschutzerklärung",
 "h_changes": "Änderungen",
 "p_changes": "Ändert sich diese Erklärung, ändert sich das Datum oben mit. Eine Änderung, die Ihre Privatsphäre einschränkte, käme mit einer neuen Version der App und stünde in deren Versionshinweisen.",
 "h_contact": "Kontakt",
 "p_contact": "Fragen zu dieser Erklärung oder dazu, was die App mit irgendetwas tut: {support}.",
 "support": "schreiben Sie uns",
 "governing": "Dies ist eine Übersetzung. Maßgeblich ist im Zweifel die englische Fassung: {link}.",
},
"fr": {
 "title": "Politique de confidentialité", "meta": "TappyMusic ne collecte rien. Aucune analyse, aucun traceur, aucun compte, et aucune donnée ne quitte l’appareil.",
 "h": "Politique de confidentialité",
 "updated": "Dernière mise à jour le 2&nbsp;août&nbsp;2026. S’applique à l’app iOS TappyMusic et à ce site.",
 "note": "<strong>TappyMusic ne collecte rien.</strong> Aucun SDK d’analyse, aucun rapport de plantage, aucune publicité, aucun traceur, aucun compte. L’app n’émet aucune requête réseau de sa propre initiative — le seul serveur auquel elle parle est l’App&nbsp;Store d’Apple, et uniquement lors d’un achat ou d’une restauration.",
 "h_device": "Ce qui reste sur votre appareil",
 "p_device": "Tout. Précisément :",
 "list": [
  "Les morceaux joués et l’endroit où vous vous êtes arrêté",
  "Les morceaux importés depuis des fichiers MIDI, et les cliparts que vous créez",
  "Vos réglages — instrument, tempo, packs présents sur l’étagère, aides à l’apprentissage activées ou non",
  "Les sauvegardes que vous choisissez d’enregistrer : de simples fichiers zip, écrits là où vous les mettez",
 ],
 "p_device_after": "Rien n’est envoyé nulle part. Supprimer l’app supprime tout cela : c’est pourquoi l’app propose une sauvegarde que vous contrôlez.",
 "h_purchases": "Achats",
 "p_purchases": "Les packs de mélodies, l’import, les cliparts et TappyMusic&nbsp;Pro sont des achats uniques entièrement gérés par Apple. Nous ne voyons jamais vos moyens de paiement, votre compte Apple ni votre nom. L’app demande à Apple ce que vous possédez et conserve la réponse sur l’appareil, pour que vos achats continuent de fonctionner hors ligne.",
 "p_family": "Les achats sont partageables en famille. Si un membre de votre groupe familial partage un achat avec vous, Apple indique à l’app que vous y avez droit — et rien sur l’identité de cette personne.",
 "h_children": "Enfants",
 "p_children": "L’app est conçue pour les enfants et classée 4+. Elle ne collecte aucune information personnelle, de personne, à aucun âge. Il n’y a ni discussion, ni contenu partagé créé par l’utilisateur, ni fonction sociale, ni navigateur web, ni publicité. Les cliparts qu’un enfant compose à partir d’emoji restent sur l’appareil.",
 "h_api": "API à justification obligatoire",
 "p_api": "Apple exige de déclarer certaines API et l’usage qui en est fait. TappyMusic en déclare exactement une : <code>UserDefaults</code>, motif <code>CA92.1</code> — enregistrer vos propres réglages sur votre propre appareil. La déclaration est livrée avec l’app sous le nom <code>PrivacyInfo.xcprivacy</code>, et sa liste de données collectées est vide.",
 "h_site": "Ce site",
 "p_site": "Ces pages sont des fichiers statiques servis par GitHub&nbsp;Pages. Elles ne déposent aucun cookie, n’intègrent aucun script, ne chargent ni polices ni images d’ailleurs, et n’exécutent aucune analyse. GitHub peut journaliser les requêtes à ses serveurs dans le cadre de l’exploitation du service ; voir {github}.",
 "github": "la déclaration de confidentialité de GitHub",
 "h_changes": "Modifications",
 "p_changes": "Si cette politique change, la date en haut change avec elle. Un changement réduisant votre confidentialité arriverait avec une nouvelle version de l’app et serait décrit dans ses notes de version.",
 "h_contact": "Contact",
 "p_contact": "Des questions sur cette politique, ou sur ce que fait l’app : {support}.",
 "support": "écrivez-nous",
 "governing": "Ceci est une traduction. En cas de divergence, la version anglaise fait foi : {link}.",
},
"es": {
 "title": "Política de privacidad", "meta": "TappyMusic no recoge nada. Sin analíticas, sin rastreo, sin cuentas, y ningún dato sale del dispositivo.",
 "h": "Política de privacidad",
 "updated": "Última actualización: 2&nbsp;de&nbsp;agosto&nbsp;de&nbsp;2026. Se aplica a la app de iOS TappyMusic y a este sitio.",
 "note": "<strong>TappyMusic no recoge nada.</strong> No hay SDK de analíticas, ni informes de fallos, ni publicidad, ni rastreo, ni cuenta. La app no hace ninguna petición de red por su cuenta: el único servidor con el que habla es el App&nbsp;Store de Apple, y solo al comprar o restaurar.",
 "h_device": "Qué se queda en tu dispositivo",
 "p_device": "Todo. En concreto:",
 "list": [
  "Qué canciones se han tocado y dónde lo dejaste",
  "Las canciones que importas de archivos MIDI y los cliparts que creas",
  "Tus ajustes: instrumento, tempo, qué packs están en la estantería, si las ayudas de aprendizaje están activas",
  "Las copias de seguridad que decidas guardar, que son archivos zip normales escritos donde tú los pongas",
 ],
 "p_device_after": "Nada de ello se sube a ningún sitio. Borrar la app borra todo esto, y por eso la app ofrece una copia de seguridad que controlas tú.",
 "h_purchases": "Compras",
 "p_purchases": "Los packs de melodías, la importación, los cliparts y TappyMusic&nbsp;Pro son compras únicas gestionadas por completo por Apple. Nunca vemos tus datos de pago, tu cuenta de Apple ni tu nombre. La app le pregunta a Apple qué tienes y guarda la respuesta en el dispositivo para que lo comprado siga funcionando sin conexión.",
 "p_family": "Las compras se comparten en familia. Si alguien de tu grupo familiar comparte una compra contigo, Apple le dice a la app que tienes derecho a ella, y nada sobre quién es esa persona.",
 "h_children": "Menores",
 "p_children": "La app está pensada para niños y tiene clasificación 4+. No recoge información personal de nadie, de ninguna edad. No hay chat, ni contenido de usuario que se comparta, ni función social, ni navegador web, ni publicidad. Los cliparts que un niño monta con emoji se quedan en ese dispositivo.",
 "h_api": "API que requieren justificación",
 "p_api": "Apple exige declarar ciertas API y el motivo de su uso. TappyMusic declara exactamente una: <code>UserDefaults</code>, con el motivo <code>CA92.1</code>: guardar tus propios ajustes en tu propio dispositivo. La declaración viaja con la app como <code>PrivacyInfo.xcprivacy</code>, y su lista de datos recogidos está vacía.",
 "h_site": "Este sitio web",
 "p_site": "Estas páginas son archivos estáticos servidos por GitHub&nbsp;Pages. No ponen cookies, no incrustan scripts, no cargan fuentes ni imágenes de ningún otro sitio y no ejecutan analíticas. GitHub puede registrar las peticiones a sus servidores como parte de la prestación del servicio; consulta {github}.",
 "github": "la declaración de privacidad de GitHub",
 "h_changes": "Cambios",
 "p_changes": "Si esta política cambia, la fecha de arriba cambia con ella. Un cambio que redujera tu privacidad llegaría con una versión nueva de la app y se describiría en sus notas de versión.",
 "h_contact": "Contacto",
 "p_contact": "Preguntas sobre esta política, o sobre lo que hace la app con cualquier cosa: {support}.",
 "support": "escríbenos",
 "governing": "Esto es una traducción. En caso de discrepancia, prevalece la versión en inglés: {link}.",
},
"it": {
 "title": "Informativa sulla privacy", "meta": "TappyMusic non raccoglie nulla. Nessuna analisi, nessun tracciamento, nessun account, e nessun dato lascia il dispositivo.",
 "h": "Informativa sulla privacy",
 "updated": "Ultimo aggiornamento: 2&nbsp;agosto&nbsp;2026. Vale per l’app iOS TappyMusic e per questo sito.",
 "note": "<strong>TappyMusic non raccoglie nulla.</strong> Nessun SDK di analisi, nessun rapporto sugli arresti anomali, nessuna pubblicità, nessun tracciamento, nessun account. L’app non effettua richieste di rete di propria iniziativa: l’unico server con cui parla è l’App&nbsp;Store di Apple, e solo quando compri o ripristini qualcosa.",
 "h_device": "Cosa resta sul tuo dispositivo",
 "p_device": "Tutto. Nel dettaglio:",
 "list": [
  "Quali brani sono stati suonati e dove ti sei fermato",
  "I brani importati da file MIDI e i clipart che crei",
  "Le tue impostazioni: strumento, tempo, quali pacchetti stanno sullo scaffale, se gli aiuti all’apprendimento sono attivi",
  "I backup che scegli di salvare, normali file zip scritti dove li metti tu",
 ],
 "p_device_after": "Niente di tutto ciò viene caricato da qualche parte. Cancellare l’app cancella tutto: per questo l’app offre un backup che controlli tu.",
 "h_purchases": "Acquisti",
 "p_purchases": "I pacchetti di melodie, l’importazione, i clipart e TappyMusic&nbsp;Pro sono acquisti una tantum gestiti interamente da Apple. Non vediamo mai i tuoi dati di pagamento, il tuo account Apple o il tuo nome. L’app chiede ad Apple che cosa possiedi e conserva la risposta sul dispositivo, così ciò che hai comprato continua a funzionare offline.",
 "p_family": "Gli acquisti sono condivisibili in famiglia. Se un membro del tuo gruppo famiglia condivide un acquisto con te, Apple comunica all’app che ne hai diritto — e nulla su chi sia quella persona.",
 "h_children": "Bambini",
 "p_children": "L’app è pensata per i bambini ed è classificata 4+. Non raccoglie informazioni personali da nessuno, a nessuna età. Non c’è chat, né contenuti degli utenti condivisi, né funzioni social, né browser web, né pubblicità. I clipart che un bambino compone con le emoji restano su quel dispositivo.",
 "h_api": "API con motivazione obbligatoria",
 "p_api": "Apple richiede di dichiarare certe API e il motivo del loro uso. TappyMusic ne dichiara esattamente una: <code>UserDefaults</code>, con motivo <code>CA92.1</code> — salvare le tue impostazioni sul tuo dispositivo. La dichiarazione viaggia con l’app come <code>PrivacyInfo.xcprivacy</code>, e il suo elenco di dati raccolti è vuoto.",
 "h_site": "Questo sito",
 "p_site": "Queste pagine sono file statici serviti da GitHub&nbsp;Pages. Non impostano cookie, non incorporano script, non caricano font o immagini da altrove e non eseguono analisi. GitHub può registrare le richieste ai propri server nell’ambito del servizio; vedi {github}.",
 "github": "l’informativa sulla privacy di GitHub",
 "h_changes": "Modifiche",
 "p_changes": "Se questa informativa cambia, cambia con essa la data in alto. Una modifica che riducesse la tua privacy arriverebbe con una nuova versione dell’app e sarebbe descritta nelle sue note di rilascio.",
 "h_contact": "Contatti",
 "p_contact": "Domande su questa informativa, o su cosa fa l’app con qualsiasi cosa: {support}.",
 "support": "scrivici",
 "governing": "Questa è una traduzione. In caso di difformità prevale la versione inglese: {link}.",
},
"pt": {
 "title": "Política de Privacidade", "meta": "O TappyMusic não coleta nada. Sem analytics, sem rastreamento, sem contas, e nenhum dado sai do aparelho.",
 "h": "Política de Privacidade",
 "updated": "Última atualização: 2&nbsp;de&nbsp;agosto&nbsp;de&nbsp;2026. Vale para o app iOS TappyMusic e para este site.",
 "note": "<strong>O TappyMusic não coleta nada.</strong> Não há SDK de analytics, nem relatório de falhas, nem publicidade, nem rastreamento, nem conta. O app não faz nenhuma requisição de rede por conta própria — o único servidor com que ele fala é a App&nbsp;Store da Apple, e só quando você compra ou restaura algo.",
 "h_device": "O que fica no seu aparelho",
 "p_device": "Tudo. Especificamente:",
 "list": [
  "Quais músicas foram tocadas e onde você parou",
  "As músicas que você importa de arquivos MIDI e os cliparts que você cria",
  "Seus ajustes: instrumento, andamento, quais pacotes estão na estante, se os apoios de aprendizado estão ligados",
  "Os backups que você escolher salvar, que são arquivos zip comuns gravados onde você quiser",
 ],
 "p_device_after": "Nada disso é enviado a lugar algum. Apagar o app apaga tudo isso — por isso o app oferece um backup que você controla.",
 "h_purchases": "Compras",
 "p_purchases": "Pacotes de melodias, importação, cliparts e o TappyMusic&nbsp;Pro são compras únicas processadas inteiramente pela Apple. Nunca vemos seus dados de pagamento, sua conta Apple ou seu nome. O app pergunta à Apple o que você possui e guarda a resposta no aparelho, para que o que você comprou continue funcionando offline.",
 "p_family": "As compras são compartilháveis com a família. Se alguém do seu grupo familiar compartilhar uma compra com você, a Apple informa ao app que você tem direito a ela — e nada sobre quem é essa pessoa.",
 "h_children": "Crianças",
 "p_children": "O app é feito para crianças e tem classificação 4+. Ele não coleta informações pessoais de ninguém, de nenhuma idade. Não há bate-papo, nem conteúdo de usuário compartilhado, nem função social, nem navegador, nem publicidade. Os cliparts que uma criança monta com emojis ficam naquele aparelho.",
 "h_api": "APIs de motivo obrigatório",
 "p_api": "A Apple exige que os apps declarem certas APIs e o motivo de uso. O TappyMusic declara exatamente uma: <code>UserDefaults</code>, com o motivo <code>CA92.1</code> — guardar seus próprios ajustes no seu próprio aparelho. A declaração vai junto com o app como <code>PrivacyInfo.xcprivacy</code>, e a lista de dados coletados está vazia.",
 "h_site": "Este site",
 "p_site": "Estas páginas são arquivos estáticos servidos pelo GitHub&nbsp;Pages. Elas não gravam cookies, não incorporam scripts, não carregam fontes nem imagens de outros lugares e não executam analytics. O GitHub pode registrar as requisições a seus servidores como parte da operação do serviço; veja {github}.",
 "github": "a declaração de privacidade do GitHub",
 "h_changes": "Alterações",
 "p_changes": "Se esta política mudar, a data no topo muda junto. Uma mudança que reduzisse sua privacidade viria com uma nova versão do app e seria descrita nas notas dessa versão.",
 "h_contact": "Contato",
 "p_contact": "Dúvidas sobre esta política, ou sobre o que o app faz com qualquer coisa: {support}.",
 "support": "fale conosco",
 "governing": "Esta é uma tradução. Em caso de divergência, prevalece a versão em inglês: {link}.",
},
"ja": {
 "title": "プライバシーポリシー", "meta": "TappyMusic は何も収集しません。解析なし、トラッキングなし、アカウントなし。データが端末から出ることはありません。",
 "h": "プライバシーポリシー",
 "updated": "最終更新：2026年8月2日。iOS アプリ TappyMusic と本サイトに適用されます。",
 "note": "<strong>TappyMusic は何も収集しません。</strong> 解析 SDK も、クラッシュレポートも、広告も、トラッキングも、アカウントもありません。アプリが自ら通信することはなく、唯一やり取りする相手は Apple の App&nbsp;Store で、購入または復元のときだけです。",
 "h_device": "端末に残るもの",
 "p_device": "すべてです。具体的には：",
 "list": [
  "どの曲を弾いたか、どこまで進んだか",
  "MIDI ファイルから取りこんだ曲と、作ったクリップアート",
  "設定——楽器、テンポ、棚に並んでいるパック、れんしゅう機能のオンオフ",
  "ご自身で保存したバックアップ。置いた場所に書き出される普通の zip ファイルです",
 ],
 "p_device_after": "どれも、どこにもアップロードされません。アプリを削除すればすべて消えます——だからこそ、アプリは自分で管理できるバックアップを用意しています。",
 "h_purchases": "購入について",
 "p_purchases": "曲パック、取りこみ、クリップアート、TappyMusic&nbsp;Pro はいずれも買い切りで、処理はすべて Apple が行います。お支払い情報も、Apple アカウントも、お名前も、こちらからは一切見えません。アプリは「何を所有しているか」を Apple に尋ね、その答えを端末に保存します。購入したものがオフラインでも使えるようにするためです。",
 "p_family": "購入はファミリー共有に対応しています。ご家族が購入を共有すると、Apple はアプリに「あなたに権利がある」とだけ伝えます。その人が誰かは伝えません。",
 "h_children": "お子さまについて",
 "p_children": "本アプリは子ども向けに作られており、レーティングは 4+ です。年齢を問わず、誰からも個人情報を収集しません。チャットも、共有されるユーザー投稿も、ソーシャル機能も、ウェブブラウザーも、広告もありません。お子さまが絵文字から作ったクリップアートは、その端末に留まります。",
 "h_api": "理由の記載が必要な API",
 "p_api": "Apple は、特定の API とその使用理由の申告を求めています。TappyMusic が申告しているのはただ一つ、<code>UserDefaults</code>（理由 <code>CA92.1</code>）——ご自身の設定をご自身の端末に保存するためです。この申告は <code>PrivacyInfo.xcprivacy</code> としてアプリに同梱されており、収集データの一覧は空です。",
 "h_site": "本ウェブサイトについて",
 "p_site": "本ページは GitHub&nbsp;Pages が配信する静的ファイルです。Cookie を設定せず、スクリプトを埋め込まず、フォントや画像を外部から読み込まず、解析も行いません。GitHub はサービス運営の一環としてサーバーへのリクエストを記録する場合があります。{github} をご覧ください。",
 "github": "GitHub のプライバシーに関する声明",
 "h_changes": "変更について",
 "p_changes": "本ポリシーが変更される場合は、冒頭の日付も変わります。プライバシーを後退させる変更は新しいバージョンのアプリとともに行われ、そのバージョンのリリースノートに記載されます。",
 "h_contact": "お問い合わせ",
 "p_contact": "本ポリシーについて、またはアプリの動作についてのご質問は{support}。",
 "support": "こちらから",
 "governing": "これは翻訳です。相違がある場合は英語版が優先します：{link}。",
},
"ko": {
 "title": "개인정보 처리방침", "meta": "TappyMusic은 아무것도 수집하지 않습니다. 분석도, 추적도, 계정도 없으며 어떤 데이터도 기기를 떠나지 않습니다.",
 "h": "개인정보 처리방침",
 "updated": "최종 갱신: 2026년 8월 2일. iOS 앱 TappyMusic과 이 웹사이트에 적용됩니다.",
 "note": "<strong>TappyMusic은 아무것도 수집하지 않습니다.</strong> 분석 SDK도, 크래시 리포터도, 광고도, 추적도, 계정도 없습니다. 앱이 스스로 네트워크 요청을 하는 일은 없으며, 통신하는 유일한 상대는 Apple의 App&nbsp;Store, 그것도 구입하거나 복원할 때뿐입니다.",
 "h_device": "기기에 남는 것",
 "p_device": "전부입니다. 구체적으로는:",
 "list": [
  "어떤 곡을 연주했고 어디까지 진행했는지",
  "MIDI 파일에서 가져온 곡과 직접 만든 클립아트",
  "설정 — 악기, 빠르기, 선반에 놓인 팩, 학습 도우미의 켜짐 여부",
  "직접 저장한 백업. 원하는 위치에 기록되는 평범한 zip 파일입니다",
 ],
 "p_device_after": "어느 것도 어디로도 업로드되지 않습니다. 앱을 지우면 전부 사라지며, 그래서 앱은 사용자가 직접 관리하는 백업을 제공합니다.",
 "h_purchases": "구입",
 "p_purchases": "멜로디 팩, 가져오기, 클립아트, TappyMusic&nbsp;Pro는 모두 한 번만 구입하는 항목이며 처리는 전적으로 Apple이 합니다. 결제 정보도, Apple 계정도, 이름도 저희는 보지 않습니다. 앱은 무엇을 소유했는지 Apple에 묻고 그 답을 기기에 저장합니다. 구입한 것이 오프라인에서도 계속 작동하도록 하기 위해서입니다.",
 "p_family": "구입은 가족 공유가 됩니다. 가족 그룹의 누군가가 구입을 공유하면, Apple은 앱에 “권한이 있다”는 사실만 알려 줍니다. 그 사람이 누구인지는 알려 주지 않습니다.",
 "h_children": "어린이",
 "p_children": "이 앱은 어린이를 위해 만들어졌으며 4+ 등급입니다. 나이를 불문하고 누구에게서도 개인정보를 수집하지 않습니다. 채팅도, 공유되는 사용자 제작물도, 소셜 기능도, 웹 브라우저도, 광고도 없습니다. 아이가 이모지로 만든 클립아트는 그 기기에 남습니다.",
 "h_api": "사유 명시가 필요한 API",
 "p_api": "Apple은 특정 API와 그 사용 사유를 밝히도록 요구합니다. TappyMusic이 밝히는 것은 단 하나, <code>UserDefaults</code>이며 사유는 <code>CA92.1</code> — 사용자의 설정을 사용자의 기기에 저장하기 위함입니다. 이 선언은 <code>PrivacyInfo.xcprivacy</code>로 앱에 함께 담겨 있고, 수집 데이터 목록은 비어 있습니다.",
 "h_site": "이 웹사이트",
 "p_site": "이 페이지들은 GitHub&nbsp;Pages가 제공하는 정적 파일입니다. 쿠키를 남기지 않고, 스크립트를 넣지 않으며, 다른 곳에서 글꼴이나 이미지를 불러오지 않고, 분석도 하지 않습니다. GitHub은 서비스 운영의 일환으로 서버 요청을 기록할 수 있습니다. {github}를 참고하세요.",
 "github": "GitHub의 개인정보 보호 성명",
 "h_changes": "변경",
 "p_changes": "이 방침이 바뀌면 맨 위의 날짜도 함께 바뀝니다. 개인정보 보호를 약화하는 변경은 새 버전의 앱과 함께 이루어지며, 그 버전의 릴리스 노트에 설명됩니다.",
 "h_contact": "문의",
 "p_contact": "이 방침에 대한, 또는 앱이 무엇을 하는지에 대한 질문은 {support}.",
 "support": "이곳으로 보내 주세요",
 "governing": "이 문서는 번역본입니다. 내용이 다를 경우 영어판이 우선합니다: {link}.",
},
"el": {
 "title": "Πολιτική απορρήτου", "meta": "Το TappyMusic δεν συλλέγει τίποτα. Καμία ανάλυση, καμία παρακολούθηση, κανένας λογαριασμός, και κανένα δεδομένο δεν φεύγει από τη συσκευή.",
 "h": "Πολιτική απορρήτου",
 "updated": "Τελευταία ενημέρωση: 2&nbsp;Αυγούστου&nbsp;2026. Ισχύει για την εφαρμογή iOS TappyMusic και για αυτόν τον ιστότοπο.",
 "note": "<strong>Το TappyMusic δεν συλλέγει τίποτα.</strong> Δεν υπάρχει SDK ανάλυσης, ούτε αναφορά σφαλμάτων, ούτε διαφήμιση, ούτε παρακολούθηση, ούτε λογαριασμός. Η εφαρμογή δεν κάνει από μόνη της καμία αίτηση δικτύου — ο μόνος διακομιστής με τον οποίο μιλά είναι το App&nbsp;Store της Apple, και μόνο όταν αγοράζεις ή επαναφέρεις κάτι.",
 "h_device": "Τι μένει στη συσκευή σου",
 "p_device": "Τα πάντα. Συγκεκριμένα:",
 "list": [
  "Ποια τραγούδια παίχτηκαν και πού σταμάτησες",
  "Τα τραγούδια που εισάγεις από αρχεία MIDI και τα κλιπάρτ που φτιάχνεις",
  "Οι ρυθμίσεις σου — όργανο, ταχύτητα, ποια πακέτα είναι στο ράφι, αν είναι ανοιχτά τα βοηθήματα μάθησης",
  "Τα αντίγραφα που επιλέγεις να αποθηκεύσεις: συνηθισμένα αρχεία zip, γραμμένα όπου τα βάλεις",
 ],
 "p_device_after": "Τίποτα από αυτά δεν ανεβαίνει πουθενά. Η διαγραφή της εφαρμογής τα σβήνει όλα — γι' αυτό η εφαρμογή προσφέρει ένα αντίγραφο που ελέγχεις εσύ.",
 "h_purchases": "Αγορές",
 "p_purchases": "Τα πακέτα μελωδιών, η εισαγωγή, τα κλιπάρτ και το TappyMusic&nbsp;Pro είναι εφάπαξ αγορές που τις διαχειρίζεται εξ ολοκλήρου η Apple. Δεν βλέπουμε ποτέ τα στοιχεία πληρωμής σου, τον λογαριασμό Apple ή το όνομά σου. Η εφαρμογή ρωτά την Apple τι κατέχεις και κρατά την απάντηση στη συσκευή, ώστε ό,τι αγόρασες να δουλεύει και εκτός σύνδεσης.",
 "p_family": "Οι αγορές μοιράζονται με την οικογένεια. Αν κάποιο μέλος της οικογενειακής σου ομάδας μοιραστεί μια αγορά μαζί σου, η Apple λέει στην εφαρμογή ότι δικαιούσαι — και τίποτα για το ποιος είναι αυτός.",
 "h_children": "Παιδιά",
 "p_children": "Η εφαρμογή είναι φτιαγμένη για παιδιά και έχει χαρακτηρισμό 4+. Δεν συλλέγει προσωπικές πληροφορίες από κανέναν, σε καμία ηλικία. Δεν υπάρχει συνομιλία, ούτε περιεχόμενο χρήστη που μοιράζεται, ούτε κοινωνική λειτουργία, ούτε περιηγητής, ούτε διαφήμιση. Τα κλιπάρτ που φτιάχνει ένα παιδί από emoji μένουν σε εκείνη τη συσκευή.",
 "h_api": "API με υποχρεωτική αιτιολόγηση",
 "p_api": "Η Apple απαιτεί τη δήλωση ορισμένων API και του λόγου χρήσης τους. Το TappyMusic δηλώνει ακριβώς ένα: το <code>UserDefaults</code>, με λόγο <code>CA92.1</code> — αποθήκευση των δικών σου ρυθμίσεων στη δική σου συσκευή. Η δήλωση συνοδεύει την εφαρμογή ως <code>PrivacyInfo.xcprivacy</code>, και η λίστα συλλεγόμενων δεδομένων της είναι κενή.",
 "h_site": "Αυτός ο ιστότοπος",
 "p_site": "Αυτές οι σελίδες είναι στατικά αρχεία που σερβίρει το GitHub&nbsp;Pages. Δεν βάζουν cookies, δεν ενσωματώνουν σενάρια, δεν φορτώνουν γραμματοσειρές ή εικόνες από αλλού και δεν τρέχουν αναλύσεις. Το GitHub μπορεί να καταγράφει αιτήματα προς τους διακομιστές του στο πλαίσιο λειτουργίας της υπηρεσίας· δες {github}.",
 "github": "τη δήλωση απορρήτου του GitHub",
 "h_changes": "Αλλαγές",
 "p_changes": "Αν αυτή η πολιτική αλλάξει, αλλάζει μαζί της και η ημερομηνία στην κορυφή. Μια αλλαγή που θα μείωνε το απόρρητό σου θα ερχόταν με νέα έκδοση της εφαρμογής και θα περιγραφόταν στις σημειώσεις έκδοσης.",
 "h_contact": "Επικοινωνία",
 "p_contact": "Ερωτήσεις για αυτή την πολιτική, ή για το τι κάνει η εφαρμογή με οτιδήποτε: {support}.",
 "support": "γράψε μας",
 "governing": "Αυτή είναι μετάφραση. Σε περίπτωση απόκλισης υπερισχύει η αγγλική έκδοση: {link}.",
},
"uk": {
 "title": "Політика приватності", "meta": "TappyMusic не збирає нічого. Без аналітики, без стеження, без облікових записів, і жодні дані не залишають пристрій.",
 "h": "Політика приватності",
 "updated": "Востаннє оновлено 2&nbsp;серпня&nbsp;2026&nbsp;року. Стосується застосунку TappyMusic для iOS і цього сайту.",
 "note": "<strong>TappyMusic не збирає нічого.</strong> Немає ні SDK аналітики, ні звітів про збої, ні реклами, ні стеження, ні облікових записів. Застосунок не робить жодного мережевого запиту з власної ініціативи — єдиний сервер, з яким він говорить, це App&nbsp;Store від Apple, і лише коли ви щось купуєте чи відновлюєте.",
 "h_device": "Що лишається на вашому пристрої",
 "p_device": "Усе. А саме:",
 "list": [
  "Які пісні грали й на чому ви зупинилися",
  "Пісні, імпортовані з файлів MIDI, і кліпарти, які ви створили",
  "Ваші налаштування — інструмент, темп, які набори стоять на полиці, чи ввімкнені навчальні підказки",
  "Резервні копії, які ви вирішили зберегти: звичайні zip-архіви, записані туди, куди ви їх покладете",
 ],
 "p_device_after": "Нічого з цього нікуди не завантажується. Видалення застосунку стирає все це — тому застосунок пропонує резервну копію, якою керуєте ви.",
 "h_purchases": "Покупки",
 "p_purchases": "Набори мелодій, імпорт, кліпарти та TappyMusic&nbsp;Pro — це одноразові покупки, які повністю обробляє Apple. Ми ніколи не бачимо ні ваших платіжних даних, ні облікового запису Apple, ні імені. Застосунок запитує в Apple, що вам належить, і зберігає відповідь на пристрої, щоб куплене працювало й без інтернету.",
 "p_family": "Покупки доступні всій сім’ї. Якщо хтось із вашої сімейної групи ділиться покупкою, Apple повідомляє застосунку лише те, що ви маєте на неї право — і нічого про те, хто ця людина.",
 "h_children": "Діти",
 "p_children": "Застосунок створено для дітей і має вікову позначку 4+. Він не збирає персональних даних ні від кого, у будь-якому віці. Немає ні чату, ні спільного користувацького вмісту, ні соціальних функцій, ні браузера, ні реклами. Кліпарти, які дитина складає з емодзі, лишаються на цьому пристрої.",
 "h_api": "API, що потребують обґрунтування",
 "p_api": "Apple вимагає декларувати певні API та причину їх використання. TappyMusic декларує рівно один: <code>UserDefaults</code> з причиною <code>CA92.1</code> — збереження ваших власних налаштувань на вашому власному пристрої. Декларація постачається із застосунком як <code>PrivacyInfo.xcprivacy</code>, і її перелік зібраних даних порожній.",
 "h_site": "Цей сайт",
 "p_site": "Ці сторінки — статичні файли, які віддає GitHub&nbsp;Pages. Вони не встановлюють cookie, не вбудовують скриптів, не завантажують шрифтів чи зображень звідкись іще й не виконують аналітики. GitHub може вести журнал запитів до своїх серверів у межах роботи сервісу; див. {github}.",
 "github": "заяву GitHub про приватність",
 "h_changes": "Зміни",
 "p_changes": "Якщо ця політика зміниться, зміниться й дата вгорі. Зміна, що звузила б вашу приватність, прийшла б із новою версією застосунку й була б описана в її примітках до випуску.",
 "h_contact": "Контакти",
 "p_contact": "Питання щодо цієї політики або щодо того, що застосунок робить із чим завгодно: {support}.",
 "support": "напишіть нам",
 "governing": "Це переклад. У разі розбіжностей чинною є англійська версія: {link}.",
},
"ru": {
 "title": "Политика приватности", "meta": "TappyMusic не собирает ничего. Без аналитики, без слежки, без учётных записей, и никакие данные не покидают устройство.",
 "h": "Политика приватности",
 "updated": "Последнее обновление: 2&nbsp;августа&nbsp;2026&nbsp;года. Относится к приложению TappyMusic для iOS и к этому сайту.",
 "note": "<strong>TappyMusic не собирает ничего.</strong> Нет ни SDK аналитики, ни отчётов о сбоях, ни рекламы, ни слежки, ни учётных записей. Приложение не делает ни одного сетевого запроса по собственной инициативе — единственный сервер, с которым оно говорит, это App&nbsp;Store от Apple, и только когда вы что-то покупаете или восстанавливаете.",
 "h_device": "Что остаётся на вашем устройстве",
 "p_device": "Всё. А именно:",
 "list": [
  "Какие песни играли и на чём вы остановились",
  "Песни, импортированные из файлов MIDI, и созданные вами клипарты",
  "Ваши настройки — инструмент, темп, какие наборы стоят на полке, включены ли обучающие подсказки",
  "Резервные копии, которые вы решили сохранить: обычные zip-архивы, записанные туда, куда вы их положите",
 ],
 "p_device_after": "Ничто из этого никуда не выгружается. Удаление приложения стирает всё это — поэтому приложение предлагает резервную копию, которой распоряжаетесь вы.",
 "h_purchases": "Покупки",
 "p_purchases": "Наборы мелодий, импорт, клипарты и TappyMusic&nbsp;Pro — разовые покупки, которые целиком обрабатывает Apple. Мы никогда не видим ни ваших платёжных данных, ни учётной записи Apple, ни имени. Приложение спрашивает у Apple, что вам принадлежит, и хранит ответ на устройстве, чтобы купленное работало и без интернета.",
 "p_family": "Покупки доступны всей семье. Если кто-то из вашей семейной группы делится покупкой, Apple сообщает приложению лишь то, что у вас есть на неё право — и ничего о том, кто этот человек.",
 "h_children": "Дети",
 "p_children": "Приложение сделано для детей и имеет возрастную оценку 4+. Оно не собирает персональных данных ни у кого, в любом возрасте. Нет ни чата, ни общего пользовательского содержимого, ни социальных функций, ни браузера, ни рекламы. Клипарты, которые ребёнок собирает из эмодзи, остаются на этом устройстве.",
 "h_api": "API, требующие обоснования",
 "p_api": "Apple требует декларировать определённые API и причину их использования. TappyMusic декларирует ровно один: <code>UserDefaults</code> с причиной <code>CA92.1</code> — хранение ваших собственных настроек на вашем собственном устройстве. Декларация поставляется с приложением как <code>PrivacyInfo.xcprivacy</code>, и её перечень собираемых данных пуст.",
 "h_site": "Этот сайт",
 "p_site": "Эти страницы — статические файлы, которые отдаёт GitHub&nbsp;Pages. Они не ставят cookie, не встраивают скриптов, не загружают шрифтов или изображений откуда-либо ещё и не выполняют аналитики. GitHub может вести журнал запросов к своим серверам в рамках работы сервиса; см. {github}.",
 "github": "заявление GitHub о приватности",
 "h_changes": "Изменения",
 "p_changes": "Если эта политика изменится, изменится и дата вверху. Изменение, сужающее вашу приватность, пришло бы с новой версией приложения и было бы описано в её примечаниях к выпуску.",
 "h_contact": "Контакты",
 "p_contact": "Вопросы об этой политике или о том, что приложение делает с чем бы то ни было: {support}.",
 "support": "напишите нам",
 "governing": "Это перевод. При расхождениях действует английская версия: {link}.",
},
}
