"""STARTING POINT — copy into your app and rewrite most of it.

Support is the least shareable of the three pages: it answers questions about
one particular app. What survives a move between apps is roughly:

    restoring purchases · what the bundle product is · deleting the app ·
    accidental purchases and Screen Time · which languages · offline

Everything else here is about a music app for children. Replace it with the
questions yours is actually asked — and if you do not know yet, ship the six
above and add to them from the first month of email.
"""

SUPPORT = {
"en": {
 "title": "Support", "meta": "Help with TappyMusic: how it works, restoring purchases, backups, and how to get in touch.",
 "h": "Support",
 "intro": 'Most questions are answered below. If yours is not, write to <a href="mailto:support@example.com?subject=Support">support@example.com</a> and say which device and iOS version you are on — it usually saves a round trip.',
 "faq": [
  ("My child taps and hears nothing.", "Check the silent switch and the volume, then check that the device is not connected to something else over Bluetooth. If the app is playing through a speaker in another room, the screen still lights up and the sound goes somewhere else."),
  ("The notes feel late.", "Bluetooth audio adds a delay that no app can remove. Use the built-in speaker or wired headphones — the difference is large and immediate. The app says so in Settings, under Audio."),
  ("I bought a pack and it is still locked.", "Open the shop and tap <strong>Restore purchases</strong>. If it is still locked, check that the device is signed in to the Apple Account that made the purchase. Purchases are Family Shareable, and Apple does not always propagate them instantly."),
  ("What is TappyMusic Pro?", "One purchase that unlocks the whole app: every melody pack, importing your own songs, and making your own cliparts. Like everything else here it is bought once and does not renew, and it is shared with your family group."),
  ("I deleted the app. Are my own songs gone?", "Songs you imported and cliparts you made live only on the device, so yes — unless you saved a backup. <strong>Backup &amp; Restore</strong> in the app writes them to an ordinary zip file you can keep in iCloud Drive or on a computer, and restore onto any device. Melody packs you bought are never lost: use Restore purchases."),
  ("Can I use my own music?", "Yes — any Standard MIDI File. The import wizard picks the tune out of the file, lets you choose the instrument and the look, and plays it to you at every step. Imported songs stay on your device and are not shared."),
  ("Is there anything my child could spend money on by accident?", "Purchases go through Apple and require whatever authentication your device is set to ask for. If you want to remove the possibility entirely, use Screen Time → Content &amp; Privacy Restrictions → iTunes &amp; App Store Purchases and set In-app Purchases to Don't Allow. Everything already bought keeps working, and so does the free pack."),
  ("Which languages does it speak?", "English, German, French, Spanish, Italian, Brazilian Portuguese, Japanese, Korean, Greek, Ukrainian and Russian. It follows your device's language."),
  ("Does it need the internet?", "No. The app works completely offline. A connection is needed only to buy or restore a purchase, because that is Apple's part of it."),
 ],
 "h_report": "Reporting a problem",
 "p_report": "Include the app version — it is at the bottom of Settings — along with your device and iOS version, and what you were doing when it happened. If it is about a particular song, its name helps a great deal.",
 "note": "This is a small app maintained by one person. Replies are not instant, but every message is read.",
},
"de": {
 "title": "Hilfe", "meta": "Hilfe zu TappyMusic: wie es funktioniert, Käufe wiederherstellen, Backups und Kontakt.",
 "h": "Hilfe",
 "intro": 'Die meisten Fragen sind unten beantwortet. Wenn Ihre nicht dabei ist, schreiben Sie an <a href="mailto:support@example.com?subject=Support">support@example.com</a> und nennen Sie Gerät und iOS-Version — das spart meist eine Rückfrage.',
 "faq": [
  ("Mein Kind tippt und hört nichts.", "Prüfen Sie den Stummschalter und die Lautstärke, und ob das Gerät gerade über Bluetooth mit etwas anderem verbunden ist. Spielt die App über einen Lautsprecher im Nebenzimmer, leuchtet der Bildschirm trotzdem und der Ton geht woanders hin."),
  ("Die Töne kommen zu spät.", "Bluetooth-Audio fügt eine Verzögerung hinzu, die keine App entfernen kann. Nutzen Sie den eingebauten Lautsprecher oder kabelgebundene Kopfhörer — der Unterschied ist groß und sofort hörbar. Die App sagt das auch in den Einstellungen unter Audio."),
  ("Ich habe ein Paket gekauft und es ist noch gesperrt.", "Öffnen Sie den Shop und tippen Sie auf <strong>Käufe wiederherstellen</strong>. Ist es weiterhin gesperrt, prüfen Sie, ob das Gerät mit dem Apple-Account angemeldet ist, mit dem gekauft wurde. Käufe sind über die Familienfreigabe teilbar, und Apple braucht dafür manchmal einen Moment."),
  ("Was ist TappyMusic Pro?", "Ein Kauf, der die ganze App freischaltet: jedes Melodiepaket, den Import eigener Lieder und eigene Cliparts. Wie alles hier ist es ein einmaliger Kauf, kein Abo, und wird mit Ihrer Familie geteilt."),
  ("Ich habe die App gelöscht. Sind meine eigenen Lieder weg?", "Importierte Lieder und selbst gemachte Cliparts liegen nur auf dem Gerät — also ja, sofern Sie kein Backup gespeichert haben. <strong>Backup &amp; Wiederherstellen</strong> in der App schreibt sie in eine gewöhnliche ZIP-Datei, die Sie in iCloud Drive oder auf dem Computer aufbewahren und auf jedem Gerät wiederherstellen können. Gekaufte Pakete gehen nie verloren: Käufe wiederherstellen."),
  ("Kann ich eigene Musik verwenden?", "Ja, jede Standard-MIDI-Datei. Der Import-Assistent holt die Melodie aus der Datei, lässt Sie Instrument und Aussehen wählen und spielt bei jedem Schritt vor. Importierte Lieder bleiben auf Ihrem Gerät und werden nicht geteilt."),
  ("Kann mein Kind aus Versehen Geld ausgeben?", "Käufe laufen über Apple und verlangen die Bestätigung, die auf Ihrem Gerät eingestellt ist. Wenn Sie das ganz ausschließen möchten: Bildschirmzeit → Beschränkungen → Käufe im iTunes &amp; App Store → In-App-Käufe: Nicht erlauben. Bereits Gekauftes funktioniert weiter, das kostenlose Paket ebenso."),
  ("Welche Sprachen spricht die App?", "Deutsch, Englisch, Französisch, Spanisch, Italienisch, brasilianisches Portugiesisch, Japanisch, Koreanisch, Griechisch, Ukrainisch und Russisch. Sie folgt der Sprache Ihres Geräts."),
  ("Braucht die App das Internet?", "Nein. Die App funktioniert vollständig offline. Eine Verbindung wird nur zum Kaufen oder Wiederherstellen gebraucht, weil das Apples Teil ist."),
 ],
 "h_report": "Ein Problem melden",
 "p_report": "Nennen Sie die App-Version — sie steht unten in den Einstellungen — dazu Gerät und iOS-Version und was Sie gerade getan haben. Geht es um ein bestimmtes Lied, hilft dessen Name sehr.",
 "note": "Dies ist eine kleine App, gepflegt von einer Person. Antworten kommen nicht sofort, aber jede Nachricht wird gelesen.",
},
"fr": {
 "title": "Aide", "meta": "Aide pour TappyMusic : fonctionnement, restauration des achats, sauvegardes et contact.",
 "h": "Aide",
 "intro": 'La plupart des questions trouvent leur réponse ci-dessous. Si ce n’est pas le cas de la vôtre, écrivez à <a href="mailto:support@example.com?subject=Support">support@example.com</a> en précisant votre appareil et votre version d’iOS — cela évite généralement un aller-retour.',
 "faq": [
  ("Mon enfant tape et n’entend rien.", "Vérifiez le bouton silence et le volume, puis si l’appareil est connecté à autre chose en Bluetooth. Si l’app joue sur une enceinte dans une autre pièce, l’écran s’allume quand même et le son part ailleurs."),
  ("Les notes semblent en retard.", "L’audio Bluetooth ajoute un délai qu’aucune app ne peut supprimer. Utilisez le haut-parleur intégré ou un casque filaire : la différence est nette et immédiate. L’app le dit aussi dans Réglages, section Audio."),
  ("J’ai acheté un pack et il est encore verrouillé.", "Ouvrez la boutique et touchez <strong>Restaurer les achats</strong>. S’il reste verrouillé, vérifiez que l’appareil est connecté au compte Apple qui a fait l’achat. Les achats sont partageables en famille, et Apple met parfois un moment à les propager."),
  ("Qu’est-ce que TappyMusic Pro ?", "Un achat qui débloque toute l’app : tous les packs de mélodies, l’import de vos morceaux et la création de cliparts. Comme tout le reste ici, c’est un achat unique, jamais un abonnement, et il est partagé avec votre famille."),
  ("J’ai supprimé l’app. Mes morceaux ont-ils disparu ?", "Les morceaux importés et les cliparts créés n’existent que sur l’appareil — donc oui, sauf si vous avez enregistré une sauvegarde. <strong>Sauvegarde et restauration</strong> les écrit dans un fichier zip ordinaire que vous pouvez garder dans iCloud Drive ou sur un ordinateur, et restaurer sur n’importe quel appareil. Les packs achetés ne sont jamais perdus : restaurez les achats."),
  ("Puis-je utiliser ma propre musique ?", "Oui, n’importe quel fichier MIDI standard. L’assistant d’import en extrait la mélodie, vous laisse choisir l’instrument et l’apparence, et vous la fait entendre à chaque étape. Les morceaux importés restent sur votre appareil et ne sont pas partagés."),
  ("Mon enfant peut-il dépenser de l’argent par accident ?", "Les achats passent par Apple et demandent l’authentification réglée sur votre appareil. Pour l’exclure totalement : Temps d’écran → Restrictions → Achats dans iTunes et l’App Store → Achats intégrés : Ne pas autoriser. Ce qui est déjà acheté continue de fonctionner, le pack gratuit aussi."),
  ("Quelles langues l’app parle-t-elle ?", "Français, anglais, allemand, espagnol, italien, portugais brésilien, japonais, coréen, grec, ukrainien et russe. Elle suit la langue de votre appareil."),
  ("L’app a-t-elle besoin d’Internet ?", "Non. Elle fonctionne entièrement hors ligne. Une connexion n’est nécessaire que pour acheter ou restaurer, parce que c’est la partie d’Apple."),
 ],
 "h_report": "Signaler un problème",
 "p_report": "Indiquez la version de l’app — elle est en bas des Réglages — ainsi que votre appareil, votre version d’iOS et ce que vous étiez en train de faire. S’il s’agit d’un morceau en particulier, son nom aide beaucoup.",
 "note": "C’est une petite app maintenue par une seule personne. Les réponses ne sont pas instantanées, mais chaque message est lu.",
},
"es": {
 "title": "Ayuda", "meta": "Ayuda con TappyMusic: cómo funciona, restaurar compras, copias de seguridad y contacto.",
 "h": "Ayuda",
 "intro": 'La mayoría de las preguntas están respondidas abajo. Si la tuya no lo está, escribe a <a href="mailto:support@example.com?subject=Support">support@example.com</a> indicando tu dispositivo y tu versión de iOS: normalmente ahorra una ida y vuelta.',
 "faq": [
  ("Mi hijo toca y no se oye nada.", "Comprueba el interruptor de silencio y el volumen, y si el dispositivo está conectado a otra cosa por Bluetooth. Si la app suena por un altavoz de otra habitación, la pantalla se ilumina igual y el sonido va a otro sitio."),
  ("Las notas suenan tarde.", "El audio por Bluetooth añade un retardo que ninguna app puede quitar. Usa el altavoz del dispositivo o auriculares con cable: la diferencia es grande e inmediata. La app también lo dice en Ajustes, en Audio."),
  ("Compré un pack y sigue bloqueado.", "Abre la tienda y toca <strong>Restaurar compras</strong>. Si sigue bloqueado, comprueba que el dispositivo tenga iniciada la sesión con la cuenta de Apple que hizo la compra. Las compras se comparten en familia, y Apple a veces tarda un poco en propagarlas."),
  ("¿Qué es TappyMusic Pro?", "Una compra que desbloquea la app entera: todos los packs de melodías, importar tus canciones y crear tus cliparts. Como todo aquí, es una compra única, nunca una suscripción, y se comparte con tu familia."),
  ("Borré la app. ¿He perdido mis canciones?", "Las canciones importadas y los cliparts creados viven solo en el dispositivo, así que sí, salvo que guardaras una copia. <strong>Copia y restauración</strong> los escribe en un zip normal que puedes guardar en iCloud Drive o en el ordenador y restaurar en cualquier dispositivo. Los packs comprados nunca se pierden: restaura las compras."),
  ("¿Puedo usar mi propia música?", "Sí, cualquier archivo MIDI estándar. El asistente de importación saca la melodía del archivo, te deja elegir el instrumento y el aspecto, y te la toca en cada paso. Las canciones importadas se quedan en tu dispositivo y no se comparten."),
  ("¿Puede mi hijo gastar dinero sin querer?", "Las compras pasan por Apple y piden la autenticación que tengas configurada. Si quieres descartarlo del todo: Tiempo de uso → Restricciones → Compras en iTunes y App Store → Compras integradas: No permitir. Lo ya comprado sigue funcionando, y el pack gratuito también."),
  ("¿Qué idiomas habla la app?", "Español, inglés, alemán, francés, italiano, portugués de Brasil, japonés, coreano, griego, ucraniano y ruso. Sigue el idioma de tu dispositivo."),
  ("¿Necesita internet?", "No. La app funciona completamente sin conexión. Solo hace falta conexión para comprar o restaurar, porque esa parte es de Apple."),
 ],
 "h_report": "Informar de un problema",
 "p_report": "Incluye la versión de la app —está al final de Ajustes— junto con tu dispositivo, tu versión de iOS y qué estabas haciendo. Si es sobre una canción concreta, su nombre ayuda mucho.",
 "note": "Es una app pequeña mantenida por una sola persona. Las respuestas no son inmediatas, pero se leen todos los mensajes.",
},
"it": {
 "title": "Aiuto", "meta": "Aiuto per TappyMusic: come funziona, ripristinare gli acquisti, backup e contatti.",
 "h": "Aiuto",
 "intro": 'Quasi tutte le domande trovano risposta qui sotto. Se la tua non c’è, scrivi a <a href="mailto:support@example.com?subject=Support">support@example.com</a> indicando dispositivo e versione di iOS: di solito risparmia un giro.',
 "faq": [
  ("Mio figlio tocca e non sente nulla.", "Controlla l’interruttore del silenzioso e il volume, poi se il dispositivo è collegato a qualcos’altro via Bluetooth. Se l’app suona da un altoparlante in un’altra stanza, lo schermo si illumina lo stesso e il suono va altrove."),
  ("Le note arrivano in ritardo.", "L’audio Bluetooth aggiunge un ritardo che nessuna app può togliere. Usa l’altoparlante integrato o cuffie con filo: la differenza è netta e immediata. L’app lo dice anche in Impostazioni, sezione Audio."),
  ("Ho comprato un pacchetto ed è ancora bloccato.", "Apri il negozio e tocca <strong>Ripristina acquisti</strong>. Se resta bloccato, controlla che il dispositivo sia collegato all’account Apple con cui hai comprato. Gli acquisti si condividono in famiglia, e ad Apple a volte serve un momento."),
  ("Che cos’è TappyMusic Pro?", "Un acquisto che sblocca tutta l’app: ogni pacchetto di melodie, l’importazione dei tuoi brani e la creazione dei clipart. Come tutto qui è un acquisto una tantum, mai un abbonamento, e si condivide con la tua famiglia."),
  ("Ho cancellato l’app. I miei brani sono persi?", "I brani importati e i clipart creati esistono solo sul dispositivo, quindi sì, a meno che tu non abbia salvato un backup. <strong>Backup e ripristino</strong> li scrive in un normale file zip che puoi tenere su iCloud Drive o sul computer e ripristinare su qualsiasi dispositivo. I pacchetti comprati non si perdono mai: ripristina gli acquisti."),
  ("Posso usare la mia musica?", "Sì, qualsiasi Standard MIDI File. La procedura di importazione estrae la melodia, ti fa scegliere strumento e aspetto e te la suona a ogni passo. I brani importati restano sul tuo dispositivo e non vengono condivisi."),
  ("Mio figlio può spendere soldi per sbaglio?", "Gli acquisti passano da Apple e richiedono l’autenticazione impostata sul dispositivo. Per escluderlo del tutto: Tempo di utilizzo → Restrizioni → Acquisti su iTunes e App Store → Acquisti in-app: Non consentire. Ciò che è già stato comprato continua a funzionare, e anche il pacchetto gratuito."),
  ("Che lingue parla l’app?", "Italiano, inglese, tedesco, francese, spagnolo, portoghese brasiliano, giapponese, coreano, greco, ucraino e russo. Segue la lingua del dispositivo."),
  ("Serve Internet?", "No. L’app funziona completamente offline. La connessione serve solo per comprare o ripristinare, perché quella è la parte di Apple."),
 ],
 "h_report": "Segnalare un problema",
 "p_report": "Indica la versione dell’app — è in fondo alle Impostazioni — insieme al dispositivo, alla versione di iOS e a cosa stavi facendo. Se riguarda un brano preciso, il suo nome aiuta molto.",
 "note": "È una piccola app curata da una persona sola. Le risposte non sono immediate, ma ogni messaggio viene letto.",
},
"pt": {
 "title": "Ajuda", "meta": "Ajuda com o TappyMusic: como funciona, restaurar compras, backups e contato.",
 "h": "Ajuda",
 "intro": 'A maioria das dúvidas está respondida abaixo. Se a sua não estiver, escreva para <a href="mailto:support@example.com?subject=Support">support@example.com</a> dizendo o aparelho e a versão do iOS — costuma poupar uma ida e volta.',
 "faq": [
  ("Meu filho toca e não sai som.", "Verifique o botão de silencioso e o volume, e se o aparelho está conectado a outra coisa por Bluetooth. Se o app estiver tocando numa caixa de som de outro cômodo, a tela acende do mesmo jeito e o som vai para outro lugar."),
  ("As notas parecem atrasadas.", "O áudio por Bluetooth acrescenta um atraso que nenhum app consegue remover. Use o alto-falante do aparelho ou fones com fio: a diferença é grande e imediata. O app também diz isso em Ajustes, em Áudio."),
  ("Comprei um pacote e ele continua bloqueado.", "Abra a loja e toque em <strong>Restaurar compras</strong>. Se continuar bloqueado, verifique se o aparelho está conectado à conta Apple que fez a compra. As compras são compartilhadas com a família, e a Apple às vezes demora um pouco."),
  ("O que é o TappyMusic Pro?", "Uma compra que desbloqueia o app inteiro: todos os pacotes de melodias, importar suas músicas e criar seus cliparts. Como tudo aqui, é uma compra única, nunca assinatura, e é compartilhada com sua família."),
  ("Apaguei o app. Minhas músicas se perderam?", "As músicas importadas e os cliparts criados só existem no aparelho, então sim, a menos que você tenha salvado um backup. <strong>Backup e restauração</strong> grava tudo num arquivo zip comum que você guarda no iCloud Drive ou no computador e restaura em qualquer aparelho. Pacotes comprados nunca se perdem: restaure as compras."),
  ("Posso usar minha própria música?", "Sim, qualquer arquivo MIDI padrão. O assistente de importação tira a melodia do arquivo, deixa você escolher o instrumento e o visual, e toca para você a cada passo. As músicas importadas ficam no seu aparelho e não são compartilhadas."),
  ("Meu filho pode gastar dinheiro sem querer?", "As compras passam pela Apple e pedem a autenticação configurada no aparelho. Para descartar isso de vez: Tempo de Uso → Restrições → Compras na iTunes Store e App Store → Compras dentro do app: Não permitir. O que já foi comprado continua funcionando, e o pacote gratuito também."),
  ("Que idiomas o app fala?", "Português, inglês, alemão, francês, espanhol, italiano, japonês, coreano, grego, ucraniano e russo. Ele segue o idioma do aparelho."),
  ("Precisa de internet?", "Não. O app funciona totalmente offline. A conexão só é necessária para comprar ou restaurar, porque essa parte é da Apple."),
 ],
 "h_report": "Relatar um problema",
 "p_report": "Inclua a versão do app — está no fim dos Ajustes — junto com o aparelho, a versão do iOS e o que você estava fazendo. Se for sobre uma música específica, o nome dela ajuda muito.",
 "note": "Este é um app pequeno, mantido por uma pessoa só. As respostas não são instantâneas, mas toda mensagem é lida.",
},
"ja": {
 "title": "サポート", "meta": "TappyMusic のサポート：使いかた、購入の復元、バックアップ、お問い合わせ。",
 "h": "サポート",
 "intro": 'ほとんどのご質問は以下で解決します。見当たらない場合は <a href="mailto:support@example.com?subject=Support">support@example.com</a> まで、機種と iOS のバージョンを添えてご連絡ください。やり取りが一往復減ります。',
 "faq": [
  ("タップしても音が出ません。", "消音スイッチと音量、そして Bluetooth で別の機器につながっていないかをご確認ください。別の部屋のスピーカーから鳴っている場合、画面は光っても音はそちらへ行きます。"),
  ("音が遅れて感じます。", "Bluetooth の音声には、どのアプリにも取り除けない遅れがあります。本体スピーカーか有線イヤホンをお使いください。違いははっきりしていて、すぐ分かります。設定の「オーディオ」にも同じ案内があります。"),
  ("パックを買ったのにまだロックされています。", "ショップを開いて<strong>購入を復元</strong>をタップしてください。それでもロックされている場合は、購入した Apple アカウントでサインインしているかご確認ください。購入はファミリー共有に対応しており、反映に少し時間がかかることがあります。"),
  ("TappyMusic Pro とは何ですか。", "アプリ全体を解除する購入です。すべての曲パック、自分の曲の取りこみ、自分のクリップアート作りが含まれます。ここにあるすべてと同じく買い切りで、サブスクではなく、ファミリーで共有できます。"),
  ("アプリを削除しました。自分の曲は消えましたか。", "取りこんだ曲と作ったクリップアートは端末の中だけにあるため、バックアップを保存していなければ失われます。アプリの<strong>バックアップと復元</strong>は、それらを普通の zip ファイルに書き出します。iCloud Drive やパソコンに保管し、どの端末にも復元できます。購入したパックは失われません——購入を復元してください。"),
  ("自分の音楽を使えますか。", "はい、標準 MIDI ファイルであれば使えます。取りこみウィザードがファイルからメロディーを取り出し、楽器と見た目を選ばせ、各ステップで聴かせます。取りこんだ曲は端末に残り、共有されません。"),
  ("子どもが誤って課金してしまうことはありますか。", "購入は Apple を通り、端末に設定された認証が求められます。完全に防ぐには、スクリーンタイム →「コンテンツとプライバシーの制限」→「iTunes および App Store での購入」→「App 内課金」を「許可しない」に設定してください。購入済みのものは引き続き使え、無料パックも使えます。"),
  ("対応言語は何ですか。", "日本語、英語、ドイツ語、フランス語、スペイン語、イタリア語、ポルトガル語、韓国語、ギリシャ語、ウクライナ語、ロシア語。端末の言語に従います。"),
  ("インターネットは必要ですか。", "いいえ。アプリは完全にオフラインで動作します。通信が必要なのは購入と復元のときだけで、それは Apple 側の処理です。"),
 ],
 "h_report": "不具合のご連絡",
 "p_report": "アプリのバージョン（設定の一番下にあります）、機種、iOS のバージョン、そして何をしていたかをお知らせください。特定の曲に関することであれば、その曲名がとても助けになります。",
 "note": "これは一人で作り、一人で手入れしている小さなアプリです。返信はすぐではありませんが、いただいたメッセージはすべて読んでいます。",
},
"ko": {
 "title": "지원", "meta": "TappyMusic 지원: 사용법, 구입 복원, 백업, 문의.",
 "h": "지원",
 "intro": '대부분의 질문은 아래에 답이 있습니다. 없다면 <a href="mailto:support@example.com?subject=Support">support@example.com</a> 로 기기와 iOS 버전을 함께 적어 보내 주세요. 보통 한 번의 왕복을 줄여 줍니다.',
 "faq": [
  ("아이가 두드리는데 소리가 안 나요.", "무음 스위치와 볼륨을 확인하시고, 기기가 블루투스로 다른 장치에 연결되어 있는지 보세요. 다른 방의 스피커로 재생 중이라면 화면은 그대로 반응하고 소리만 그쪽으로 갑니다."),
  ("음이 늦게 들려요.", "블루투스 오디오에는 어떤 앱도 없앨 수 없는 지연이 있습니다. 기기 스피커나 유선 이어폰을 쓰세요. 차이가 크고 바로 느껴집니다. 앱의 설정 ▸ 오디오에도 같은 안내가 있습니다."),
  ("팩을 샀는데 아직 잠겨 있어요.", "상점을 열고 <strong>구입 복원</strong>을 누르세요. 그래도 잠겨 있다면 구입한 Apple 계정으로 로그인되어 있는지 확인해 주세요. 구입은 가족 공유가 되며, Apple이 반영하는 데 잠시 걸릴 때가 있습니다."),
  ("TappyMusic Pro는 무엇인가요?", "앱 전체를 여는 구입입니다. 모든 멜로디 팩, 내 곡 가져오기, 나만의 클립아트 만들기가 포함됩니다. 여기 있는 모든 것과 마찬가지로 한 번만 구입하면 되고, 구독이 아니며, 가족과 공유됩니다."),
  ("앱을 지웠어요. 제 곡은 사라졌나요?", "가져온 곡과 만든 클립아트는 기기에만 있으므로, 백업을 저장하지 않았다면 사라집니다. 앱의 <strong>백업 및 복원</strong>은 그것들을 평범한 zip 파일로 저장합니다. iCloud Drive나 컴퓨터에 보관했다가 어떤 기기에든 복원할 수 있습니다. 구입한 팩은 사라지지 않습니다 — 구입 복원을 쓰세요."),
  ("제 음악을 쓸 수 있나요?", "네, 표준 MIDI 파일이면 됩니다. 가져오기 마법사가 파일에서 멜로디를 찾아내고, 악기와 모습을 고르게 하며, 단계마다 들려줍니다. 가져온 곡은 기기에 남고 공유되지 않습니다."),
  ("아이가 실수로 결제할 수 있나요?", "구입은 Apple을 거치며 기기에 설정된 인증을 요구합니다. 아예 막으려면 스크린 타임 → 콘텐츠 및 개인정보 보호 제한 → iTunes 및 App Store 구입 → 앱 내 구입: 허용 안 함으로 설정하세요. 이미 구입한 것은 계속 쓸 수 있고, 무료 팩도 그대로입니다."),
  ("어떤 언어를 지원하나요?", "한국어, 영어, 독일어, 프랑스어, 스페인어, 이탈리아어, 브라질 포르투갈어, 일본어, 그리스어, 우크라이나어, 러시아어. 기기의 언어를 따릅니다."),
  ("인터넷이 필요한가요?", "아니요. 앱은 완전히 오프라인으로 작동합니다. 연결이 필요한 것은 구입하거나 복원할 때뿐이며, 그것은 Apple의 몫입니다."),
 ],
 "h_report": "문제 알리기",
 "p_report": "앱 버전(설정 맨 아래에 있습니다)과 기기, iOS 버전, 그리고 무엇을 하던 중이었는지 알려 주세요. 특정 곡에 관한 것이라면 곡 이름이 큰 도움이 됩니다.",
 "note": "한 사람이 만들고 돌보는 작은 앱입니다. 답장이 즉시 가지는 않지만, 모든 메시지를 읽습니다.",
},
"el": {
 "title": "Βοήθεια", "meta": "Βοήθεια για το TappyMusic: πώς λειτουργεί, επαναφορά αγορών, αντίγραφα και επικοινωνία.",
 "h": "Βοήθεια",
 "intro": 'Οι περισσότερες απορίες απαντώνται παρακάτω. Αν η δική σου δεν είναι εδώ, γράψε στο <a href="mailto:support@example.com?subject=Support">support@example.com</a> αναφέροντας συσκευή και έκδοση iOS — συνήθως γλιτώνει έναν γύρο.',
 "faq": [
  ("Το παιδί μου αγγίζει και δεν ακούγεται τίποτα.", "Έλεγξε τον διακόπτη σίγασης και την ένταση, και μετά αν η συσκευή είναι συνδεδεμένη με κάτι άλλο μέσω Bluetooth. Αν η εφαρμογή παίζει σε ηχείο άλλου δωματίου, η οθόνη ανάβει κανονικά και ο ήχος πάει αλλού."),
  ("Οι νότες ακούγονται αργοπορημένες.", "Ο ήχος μέσω Bluetooth προσθέτει καθυστέρηση που καμία εφαρμογή δεν μπορεί να αφαιρέσει. Χρησιμοποίησε το ηχείο της συσκευής ή ενσύρματα ακουστικά — η διαφορά είναι μεγάλη και άμεση. Το λέει και η εφαρμογή στις Ρυθμίσεις, στην ενότητα Ήχος."),
  ("Αγόρασα ένα πακέτο και είναι ακόμη κλειδωμένο.", "Άνοιξε το κατάστημα και άγγιξε <strong>Επαναφορά αγορών</strong>. Αν παραμένει κλειδωμένο, έλεγξε ότι η συσκευή είναι συνδεδεμένη στον λογαριασμό Apple που έκανε την αγορά. Οι αγορές μοιράζονται με την οικογένεια, και η Apple κάποιες φορές αργεί λίγο."),
  ("Τι είναι το TappyMusic Pro;", "Μία αγορά που ξεκλειδώνει όλη την εφαρμογή: κάθε πακέτο μελωδιών, την εισαγωγή των τραγουδιών σου και τη δημιουργία κλιπάρτ. Όπως όλα εδώ, είναι εφάπαξ αγορά, ποτέ συνδρομή, και μοιράζεται με την οικογένειά σου."),
  ("Έσβησα την εφαρμογή. Χάθηκαν τα τραγούδια μου;", "Τα τραγούδια που εισήγαγες και τα κλιπάρτ που έφτιαξες υπάρχουν μόνο στη συσκευή — άρα ναι, εκτός αν κράτησες αντίγραφο. Η <strong>Δημιουργία και επαναφορά αντιγράφων</strong> τα γράφει σε ένα συνηθισμένο αρχείο zip που μπορείς να φυλάξεις στο iCloud Drive ή στον υπολογιστή και να επαναφέρεις σε οποιαδήποτε συσκευή. Τα αγορασμένα πακέτα δεν χάνονται ποτέ: κάνε επαναφορά αγορών."),
  ("Μπορώ να χρησιμοποιήσω δική μου μουσική;", "Ναι, οποιοδήποτε τυπικό αρχείο MIDI. Ο οδηγός εισαγωγής βγάζει τη μελωδία από το αρχείο, σε αφήνει να διαλέξεις όργανο και εμφάνιση, και σου την παίζει σε κάθε βήμα. Τα τραγούδια που εισάγεις μένουν στη συσκευή σου και δεν μοιράζονται."),
  ("Μπορεί το παιδί μου να ξοδέψει χρήματα κατά λάθος;", "Οι αγορές περνούν από την Apple και ζητούν την ταυτοποίηση που έχεις ορίσει. Για να το αποκλείσεις τελείως: Χρόνος επί οθόνης → Περιορισμοί → Αγορές σε iTunes και App Store → Αγορές εντός εφαρμογής: Να μην επιτρέπονται. Ό,τι έχει ήδη αγοραστεί συνεχίζει να δουλεύει, όπως και το δωρεάν πακέτο."),
  ("Τι γλώσσες μιλά η εφαρμογή;", "Ελληνικά, αγγλικά, γερμανικά, γαλλικά, ισπανικά, ιταλικά, πορτογαλικά Βραζιλίας, ιαπωνικά, κορεατικά, ουκρανικά και ρωσικά. Ακολουθεί τη γλώσσα της συσκευής σου."),
  ("Χρειάζεται σύνδεση στο διαδίκτυο;", "Όχι. Η εφαρμογή λειτουργεί πλήρως εκτός σύνδεσης. Σύνδεση χρειάζεται μόνο για αγορά ή επαναφορά, γιατί αυτό είναι το κομμάτι της Apple."),
 ],
 "h_report": "Αναφορά προβλήματος",
 "p_report": "Ανάφερε την έκδοση της εφαρμογής — βρίσκεται στο κάτω μέρος των Ρυθμίσεων — μαζί με τη συσκευή, την έκδοση iOS και τι έκανες εκείνη τη στιγμή. Αν αφορά συγκεκριμένο τραγούδι, το όνομά του βοηθά πολύ.",
 "note": "Είναι μια μικρή εφαρμογή που τη συντηρεί ένα άτομο. Οι απαντήσεις δεν είναι άμεσες, αλλά κάθε μήνυμα διαβάζεται.",
},
"uk": {
 "title": "Допомога", "meta": "Допомога з TappyMusic: як це працює, відновлення покупок, резервні копії та контакти.",
 "h": "Допомога",
 "intro": 'Більшість питань має відповідь нижче. Якщо вашого тут немає, напишіть на <a href="mailto:support@example.com?subject=Support">support@example.com</a> і вкажіть пристрій та версію iOS — це зазвичай економить одне листування.',
 "faq": [
  ("Дитина торкається, але нічого не чути.", "Перевірте перемикач беззвучного режиму й гучність, а потім — чи не підключено пристрій по Bluetooth до чогось іншого. Якщо застосунок грає через колонку в іншій кімнаті, екран усе одно світиться, а звук іде туди."),
  ("Ноти звучать із запізненням.", "Звук через Bluetooth додає затримку, яку жоден застосунок не прибере. Скористайтеся вбудованим динаміком або дротовими навушниками — різниця велика й помітна одразу. Застосунок каже про це і в Параметрах, у розділі «Звук»."),
  ("Я купив набір, а він досі заблокований.", "Відкрийте магазин і торкніться <strong>Відновити покупки</strong>. Якщо він і далі заблокований, перевірте, чи ви увійшли обліковим записом Apple, яким робили покупку. Покупки доступні всій сім’ї, і Apple інколи потребує часу, щоб це поширити."),
  ("Що таке TappyMusic Pro?", "Одна покупка, що відкриває весь застосунок: усі набори мелодій, імпорт власних пісень і створення власних кліпартів. Як і все тут, це одноразова покупка, а не підписка, і вона доступна всій сім’ї."),
  ("Я видалив застосунок. Мої пісні зникли?", "Імпортовані пісні та створені кліпарти є лише на пристрої — тож так, якщо ви не зберегли резервну копію. <strong>Копіювання та відновлення</strong> записує їх у звичайний zip-архів, який можна тримати в iCloud Drive чи на комп’ютері й відновити на будь-якому пристрої. Куплені набори не втрачаються ніколи: відновіть покупки."),
  ("Чи можу я використати власну музику?", "Так, будь-який стандартний файл MIDI. Помічник імпорту витягає мелодію з файлу, дає обрати інструмент і вигляд і програє її на кожному кроці. Імпортовані пісні лишаються на вашому пристрої й нікуди не передаються."),
  ("Чи може дитина випадково витратити гроші?", "Покупки проходять через Apple і вимагають того підтвердження, яке налаштоване на пристрої. Щоб виключити це повністю: Екранний час → Обмеження → Покупки в iTunes та App Store → Вбудовані покупки: Не дозволяти. Усе вже придбане працює далі, безкоштовний набір теж."),
  ("Якими мовами говорить застосунок?", "Українською, англійською, німецькою, французькою, іспанською, італійською, португальською, японською, корейською, грецькою та російською. Він слідує мові вашого пристрою."),
  ("Чи потрібен інтернет?", "Ні. Застосунок працює цілком без інтернету. З’єднання потрібне лише щоб купити або відновити покупку, бо це частина Apple."),
 ],
 "h_report": "Повідомити про проблему",
 "p_report": "Вкажіть версію застосунку — вона внизу Параметрів — а також пристрій, версію iOS і що саме ви робили. Якщо йдеться про конкретну пісню, її назва дуже допоможе.",
 "note": "Це невеликий застосунок, який підтримує одна людина. Відповіді не миттєві, але кожне повідомлення прочитане.",
},
"ru": {
 "title": "Помощь", "meta": "Помощь с TappyMusic: как это работает, восстановление покупок, резервные копии и контакты.",
 "h": "Помощь",
 "intro": 'На большинство вопросов ответы ниже. Если вашего здесь нет, напишите на <a href="mailto:support@example.com?subject=Support">support@example.com</a> и укажите устройство и версию iOS — обычно это экономит одну переписку.',
 "faq": [
  ("Ребёнок касается, а звука нет.", "Проверьте переключатель бесшумного режима и громкость, а затем — не подключено ли устройство по Bluetooth к чему-то ещё. Если приложение играет через колонку в другой комнате, экран всё равно светится, а звук уходит туда."),
  ("Ноты звучат с опозданием.", "Звук через Bluetooth добавляет задержку, которую не уберёт ни одно приложение. Используйте встроенный динамик или проводные наушники — разница большая и заметна сразу. Приложение говорит об этом и в Настройках, в разделе «Звук»."),
  ("Я купил набор, а он всё ещё заблокирован.", "Откройте магазин и нажмите <strong>Восстановить покупки</strong>. Если он по-прежнему заблокирован, проверьте, что вы вошли под той учётной записью Apple, которой покупали. Покупки доступны всей семье, и Apple иногда требуется время, чтобы это распространить."),
  ("Что такое TappyMusic Pro?", "Одна покупка, открывающая всё приложение: все наборы мелодий, импорт своих песен и создание своих клипартов. Как и всё здесь, это разовая покупка, а не подписка, и она доступна всей семье."),
  ("Я удалил приложение. Мои песни пропали?", "Импортированные песни и созданные клипарты есть только на устройстве — так что да, если вы не сохранили резервную копию. <strong>Копирование и восстановление</strong> записывает их в обычный zip-архив, который можно держать в iCloud Drive или на компьютере и восстановить на любом устройстве. Купленные наборы не теряются никогда: восстановите покупки."),
  ("Могу ли я использовать свою музыку?", "Да, любой стандартный файл MIDI. Помощник импорта достаёт мелодию из файла, даёт выбрать инструмент и облик и проигрывает её на каждом шаге. Импортированные песни остаются на вашем устройстве и никуда не передаются."),
  ("Может ли ребёнок случайно потратить деньги?", "Покупки идут через Apple и требуют того подтверждения, которое настроено на устройстве. Чтобы исключить это полностью: Экранное время → Ограничения → Покупки в iTunes и App Store → Встроенные покупки: Не разрешать. Всё уже купленное продолжает работать, бесплатный набор тоже."),
  ("На каких языках говорит приложение?", "На русском, английском, немецком, французском, испанском, итальянском, португальском, японском, корейском, греческом и украинском. Оно следует языку вашего устройства."),
  ("Нужен ли интернет?", "Нет. Приложение работает полностью без интернета. Соединение нужно только чтобы купить или восстановить покупку, потому что это часть Apple."),
 ],
 "h_report": "Сообщить о проблеме",
 "p_report": "Укажите версию приложения — она внизу Настроек — а также устройство, версию iOS и что вы делали. Если речь о конкретной песне, её название очень поможет.",
 "note": "Это небольшое приложение, которое поддерживает один человек. Ответы приходят не мгновенно, но каждое сообщение прочитано.",
},
}
